import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    manage: 'Manage',
    reports: 'Reports',
    analytics: 'Analytics',
    logout: 'Sign Out',
    profile: 'Profile',
    changePassword: 'Change Password',
    users: 'Users',
    adminDashboard: 'Admin Panel',
    managerDashboard: 'Manager Dashboard',
    
    // Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to access your declaration management system',
    username: 'Username',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    login: 'Sign In',
    invalidCredentials: 'Invalid credentials. Please try again.',
    
    // Dashboard
    systemTitle: 'Declaration Management System',
    streamlineWorkflow: 'Streamline Your Declaration Workflow',
    streamlineDesc: 'Transform manual tracking into intelligent digital workflows with real-time status updates, automated approvals, and comprehensive reporting.',
    unsigned: 'Unsigned',
    pending: 'Pending',
    approved: 'Approved',
    archived: 'Archived',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    addDeclaration: 'New Declaration',
    viewReports: 'View Reports',
    welcome: 'Welcome',
    all: 'All',
    recentDeclarations: 'Recent Declarations',
    exportAllDeclarations: 'Export All Declarations',
    
    // Admin Dashboard
    adminDashboardTitle: 'Admin Panel',
    adminDashboardSubtitle: 'Comprehensive overview of system statistics and activities',
    totalUsers: 'Total Users',
    allSystemAccounts: 'All registered accounts',
    systemAdmins: 'Administrators',
    fullAccess: 'Full system access',
    managers: 'Managers',
    managerialPermissions: 'Managerial permissions',
    totalDeclarations: 'Total Declarations',
    allDeclarations: 'All declarations in system',
    userDistribution: 'User Distribution by Role',
    rolePercentage: 'Percentage breakdown by role type',
    declarationDistribution: 'Declaration Status Distribution',
    countByStage: 'Count of declarations by workflow stage',
    recentActivities: 'Recent Activities',
    latestSystemChanges: 'Latest system changes and updates',
    noRecentActivities: 'No recent activities to display',
    statistics: 'Statistics',
    allYears: 'All Years',
    selectYear: 'Select Year',
    userManagement: 'User Management',
    
    // User Management
    permissionsGuide: 'Permissions Guide',
    systemAdmin: 'Administrator',
    subManager: 'Manager',
    regularUser: 'Standard User',
    usersCount: 'Users',
    refresh: 'Refresh',
    addUser: 'Add User',
    addNewUser: 'Add New User',
    createUserAccount: 'Create a new user account and assign permissions',
    email: 'Email Address',
    role: 'Role',
    creationDate: 'Created On',
    cancel: 'Cancel',
    create: 'Create',
    creating: 'Creating...',
    createUser: 'Create User',
    areYouSure: 'Confirm Action',
    deleteRoleWarning: 'This will remove the user\'s permissions. To completely delete the user, access the database administration panel.',
    delete: 'Delete',
    deletePermissions: 'Remove Permissions',
    sendInvitation: 'Send Invitation',
    invitationSent: 'Invitation sent successfully to',
    invitationFailed: 'Failed to send invitation. Please try again.',
    sending: 'Sending...',
    invitationDescription: 'An invitation email will be sent to this address',
    howItWorks: 'How it works:',
    invitationStep1: 'Invitation email is sent to the user',
    invitationStep2: 'User clicks the activation link',
    invitationStep3: 'User sets their secure password',
    invitationStep4: 'User can now access the system',
    
    // Permissions
    viewAllDeclarations: 'View all declarations',
    createEditDeleteDeclarations: 'Create, edit, and delete declarations',
    changeAnyDeclarationStatus: 'Update any declaration status',
    manageAllUsers: 'Manage all users',
    addDeleteUsers: 'Add and remove users',
    changeUserPermissions: 'Modify user permissions',
    viewReportsStatistics: 'Access reports and analytics',
    fullSystemAccess: 'Full administrative access',
    createEditDeclarations: 'Create and edit declarations',
    changeAllDeclarationStatus: 'Update all declaration statuses',
    viewUserInformation: 'View user information',
    createNewDeclarations: 'Create new declarations',
    editOwnDeclarations: 'Edit own declarations only',
    changeOwnDeclarationStatus: 'Update own declaration status',
    viewOwnProfile: 'View personal profile',
    
    // Status Labels
    draft: 'Draft',
    pendingWarehouseSignature: 'Awaiting Signature',
    warehouseSigned: 'Signed',
    sentToAdminOffice: 'Sent to Office',
    receivedByAdminOffice: 'Received',
    returnedToWarehouse: 'Returned for Modification',
    returnedForModification: 'Returned for Modification',
    rejected: 'Rejected',
    pendingSignature: 'Awaiting Signature',
    signed: 'Signed',
    sentToOffice: 'Sent to Office',
    // Dynamic status labels based on declaration type
    pendingDelivererSignature: 'Awaiting Deliverer Signature',
    pendingReceiverSignature: 'Awaiting Receiver Signature',
    signedByDeliverer: 'Signed by Deliverer',
    signedByReceiver: 'Signed by Receiver',
    
    // Declaration Details
    declarationDetails: 'Declaration Details',
    declarationInfo: 'Declaration Information',
    declarationNumber: 'Declaration ID',
    updateStatus: 'Update Status',
    currentStatus: 'Current Status',
    timeline: 'Timeline',
    viewTimeline: 'View Timeline',
    backToManage: 'Back to Manage',
    createdBy: 'Created By',
    lastUpdated: 'Last Updated',
    statusHistory: 'Status History',
    changedBy: 'Changed By',
    changedAt: 'Changed At',
    oldStatus: 'Previous Status',
    newStatus: 'New Status',
    notes: 'Notes',
    noNotes: 'No notes available',
    statusUpdated: 'Status updated successfully',
    statusUpdateFailed: 'Failed to update status. Please try again.',
    declarationNotFound: 'Declaration not found',
    
    // Create Declaration
    createDeclaration: 'Create Declaration',
    createNewDeclaration: 'Create New Declaration',
    enterDeclarationDetails: 'Enter declaration details below',
    declarationNumberLabel: 'Declaration ID',
    declarationType: 'Type',
    selectType: 'Select Type',
    entrance: 'Inbound',
    exit: 'Outbound',
    initialStatus: 'Initial Status',
    selectStatus: 'Select Status',
    declarationCreated: 'Declaration created successfully',
    declarationCreationFailed: 'Failed to create declaration. Please try again.',
    numberTooShort: 'Declaration ID must be at least 3 digits',
    numberTooLong: 'Declaration ID is too long',
    numbersOnly: 'Only numeric characters allowed',
    mustSelectType: 'Please select a declaration type',
    mustLogin: 'Authentication required',
    numberExists: 'This Declaration ID already exists',
    
    // Login/Signup
    signup: 'Sign Up',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signupSuccess: 'Account created successfully',
    signupFailed: 'Account creation failed. Please try again.',
    enterUsername: 'Please enter your username',
    loggingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    
    // Messages
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    noData: 'No data available',
    loadingData: 'Loading data...',
    userRoleUpdated: 'User role updated successfully',
    userCreatedSuccess: 'User created successfully',
    fillAllFields: 'Please complete all required fields',
    userCreationFailed: 'User creation failed. Please try again.',
    permissionsDeleted: 'Permissions removed successfully',
    userDeleted: 'User deleted successfully',
    userDeactivated: 'User deactivated successfully',
    userReactivated: 'User reactivated successfully',
    cannotDeleteSelf: 'Cannot delete your own account',
    notAuthorizedToDelete: 'You are not authorized to delete users',
    cannotDeleteUserLinkedData: 'Cannot delete user with linked data',
    cannotDeleteUser: 'Cannot Delete User',
    userHasLinkedDataDescription: 'This user has linked data in the system and cannot be deleted permanently. You can deactivate the user instead.',
    linkedDataSummary: 'Linked Data',
    items: 'items',
    alternativeAction: 'Alternative Action',
    deactivateUserDescription: 'Deactivating the user will prevent login while preserving all their data. The user can be reactivated later if needed.',
    deactivateUser: 'Deactivate User',
    reactivateUser: 'Reactivate User',
    showInactiveUsers: 'Show Inactive Users',
    confirmDeleteUser: 'Confirm Delete User',
    deleteUserWarning: 'Are you sure you want to permanently delete this user?',
    deleteUserPermanentWarning: 'This action cannot be undone. All user data will be permanently deleted.',
    deleteUser: 'Delete User',
    you: 'You',
    
    // Dashboard Specific
    dashboardSubtitle: 'Track and manage all your declarations in one place',
    manageUsers: 'Manage Users',
    viewAll: 'View All',
    noDeclarations: 'No declarations found',
    
    // Manage Page
    manageDeclarations: 'Manage Declarations',
    manageSubtitle: 'View, filter, and manage all system declarations',
    searchPlaceholder: 'Search by ID or sender...',
    filterBySender: 'Filter by Sender',
    allSenders: 'All Senders',
    filterByDate: 'Filter by Date',
    dateRange: 'Date Range',
    from: 'From',
    to: 'To',
    clearFilters: 'Clear Filters',
    selectAll: 'Select All',
    selected: 'selected',
    exportSelected: 'Export Selected',
    deleteSelected: 'Delete Selected',
    noDeclarationsFound: 'No declarations found',
    tryAdjustingFilters: 'Try adjusting your search filters',
    bulkExport: 'Bulk Export',
    
    // Reports Page
    reportsTitle: 'Reports & Analytics',
    reportsSubtitle: 'Comprehensive analysis of declarations and system performance',
    exportOptions: 'Export Options',
    statusBreakdown: 'Status Breakdown',
    declarationsOverTime: 'Declarations Over Time',
    topUsers: 'Top Contributors',
    by: 'by',
    
    // Profile Page
    myProfile: 'My Profile',
    personalInformation: 'Personal Information',
    accountSettings: 'Account Settings',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated successfully',
    passwordMismatch: 'Passwords do not match',
    saveChanges: 'Save Changes',
    profileSubtitle: 'Manage your personal information and account settings',
    accountRole: 'Account Role',
    personalData: 'Personal Information',
    usernameLabel: 'Username',
    emailLabel: 'Email',
    jobRole: 'Job Role',
    resetFields: 'Reset',
    saveProfile: 'Save Changes',
    savingProfile: 'Saving...',
    profileUpdated: 'Profile updated successfully',
    profileUpdateFailed: 'Failed to update profile',
    usernameAlreadyTaken: 'Username is already taken',
    emailAlreadyTaken: 'Email is already taken',
    dataValidationError: 'Data Validation Error',
    changePasswordTitle: 'Change Password',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    passwordMinLength: 'At least 10 characters',
    passwordUppercase: 'At least one uppercase letter',
    passwordLowercase: 'At least one lowercase letter',
    passwordNumber: 'At least one number',
    passwordSpecialChar: 'At least one special character (!@#$%^&*)',
    passwordStrength: 'Password strength',
    passwordRequirements: 'Password requirements',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    usernameHint: '2-50 characters, letters, numbers, underscores',
    pleaseWait: 'Please wait...',
    skipToContent: 'Skip to main content',
    invalidEmail: 'Invalid email address',
    invalidData: 'Invalid data entered',
    passwordChangeFailed: 'Failed to change password. Please try again.',
    passwordChangeSuccess: 'Password changed successfully',
    
    // Common Actions
    view: 'View',
    edit: 'Edit',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    close: 'Close',
    save: 'Save',
    update: 'Update',
    confirm: 'Confirm',
    
    // Manage
    declarations: 'Declarations',
    search: 'Search',
    filter: 'Filter',
    status: 'Status',
    allStatuses: 'All Statuses',
    declarationId: 'Declaration ID',
    type: 'Type',
    sender: 'Sender',
    createdDate: 'Created Date',
    actions: 'Actions',
    bulkActions: 'Bulk Actions',
    showing: 'Showing',
    of: 'of',
    results: 'results',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    overview: 'Overview',
    statusDistribution: 'Status Distribution',
    userActivity: 'User Activity',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    exportCSV: 'Export CSV',
    monthlyTrends: 'Monthly Trends',
    completionRate: 'Completion Rate',
    avgProcessingTime: 'Avg. Processing',
    days: 'days',
    savedFilters: 'Saved Filters',
    noSavedFilters: 'No saved filters',
    saveCurrentFilter: 'Save current filter',
    saveFilter: 'Save Filter',
    saveFilterDescription: 'Save your current filter settings for quick access',
    filterNamePlaceholder: 'Filter name...',
    filterSaved: 'Filter saved successfully',
    filterDeleted: 'Filter deleted',
    filterApplied: 'Filter applied',
    enterFilterName: 'Please enter a filter name',
    exportSuccess: 'Report exported successfully',
    changedDeclarationStatus: 'changed declaration status',
    userLabel: 'User',
    switchLanguage: 'Switch Language',
    
    // Navigation
    home: 'Home',
    maintenance: 'Maintenance',
    installApp: 'Install App',
    auditLog: 'Audit Log',
    checkingUpdates: 'Checking for updates',
    noUpdates: 'No updates available',
    updateAvailable: 'Update available',
    pageWillReload: 'Page will reload to apply update...',
    youUsingLatest: 'You are using the latest version',
    serviceWorkerNotRegistered: 'Service Worker not registered',
    notSupported: 'Not supported',
    browserNotSupport: 'Your browser does not support this feature',
    updateCheckFailed: 'Failed to check for updates',
    forceUpdate: 'Update Now',
    forceUpdateDescription: 'This will clear all cached data and reload the latest version of the system. Are you sure?',
    updateInProgress: 'Updating...',
    updateNow: 'Update Now',
    currentVersion: 'Current Version',
    newDesktopVersionAvailable: 'A new version of the desktop app is available',
    downloadUpdate: 'Download Update',
    later: 'Later',

    // Holiday Attendance
    holidayAttendance: 'Holiday Attendance',
    holidayAttendanceDesc: 'Manage employee attendance sheets during official holidays',
    newSheet: 'New Sheet',
    totalSheets: 'Total Sheets',
    noSheetsFound: 'No sheets found',
    sheetDetails: 'Sheet Details',
    sheetInfo: 'Sheet Info',
    workRecords: 'Work Records',
    employeesData: 'Employees Data',
    warehouseName: 'Warehouse Name',
    warehouseNumber: 'Warehouse Number',
    holidayName: 'Holiday Name',
    periodStart: 'Period Start',
    periodEnd: 'Period End',
    monthYear: 'Month / Year',
    monthYearPlaceholder: 'e.g. March 2026',
    sheetCreated: 'Sheet created successfully',
    sheetUpdated: 'Sheet updated successfully',
    saveSheetFirst: 'Please save the sheet first',
    addRecord: 'Add Record',
    workType: 'Work Type',
    workDate: 'Work Date',
    presentEmployees: 'Present Employees',
    enterEmployeeNames: 'Enter employee names...',
    noRecords: 'No records yet',
    totalWorkDays: 'Total Work Days',
    deleteSheet: 'Delete Sheet',
    deleteSheetConfirm: 'Are you sure you want to delete this sheet?',
    deleteRecord: 'Delete Record',
    deleteRecordConfirm: 'Are you sure you want to delete this record?',
    deleteEmployeeConfirm: 'Are you sure you want to delete this employee?',
    printPreview: 'Print Preview',
    serial: 'Serial',

    // Archive Files
    archiveFiles: 'Archive Files',
    archiveFilesManagement: 'Archive File Management',
    addArchiveFile: 'Add Archive File',
    archiveNumber: 'Archive Number',
    archiveDescription: 'Description',
    declarationsCount: 'Declaration Count',
    createdAt: 'Created At',
    noArchiveFiles: 'No archive files found',
    addFirstArchiveFile: 'Create your first archive file',
    enterArchiveNumber: 'Enter archive number',
    enterDescription: 'Enter description (optional)',
    add: 'Add',
    adding: 'Adding...',
    archiveFileAdded: 'Archive file created successfully',
    archiveFileDeleted: 'Archive file deleted successfully',
    archiveFileExists: 'This archive number already exists',
    cannotDeleteArchive: 'Cannot delete archive with linked declarations',
    confirmDeleteArchive: 'Are you sure you want to delete this archive file?',
    unknown: 'Unknown',
    noRecentDeclarations: 'No recent declarations',
    
    // Manage Page Extended
    trashBin: 'Trash',
    allSendersFilter: 'All Senders',
    exportExcelBtn: 'Export to Excel',
    exportPDFBtn: 'Export to PDF',
    manageArchiveFiles: 'Manage archive files and declarations',
    movedToTrash: 'Declaration moved to trash',
    alreadyDeleted: 'Declaration already deleted',
    
    // Maintenance
    maintenanceSystem: 'Maintenance System',
    itemName: 'Item Name',
    frequency: 'Frequency',
    lastMaintenance: 'Last Maintenance',
    nextMaintenance: 'Next Maintenance',
    estimatedCost: 'Estimated Cost',
    active: 'Active',
    inactive: 'Inactive',
    viewDetails: 'View Details',
    addMaintenanceItem: 'Add Maintenance Item',
    addAsset: 'Add Asset',
    addVendor: 'Add Vendor',
    assetName: 'Asset Name',
    vendorName: 'Vendor Name',
    contactPerson: 'Contact Person',
    contactInfo: 'Contact Information',
    specialization: 'Specialization',
    location: 'Location',
    site: 'Site',
    code: 'Code',
    phone: 'Phone',
    
    // Maintenance Status
    done: 'Completed',
    notRequired: 'Not Required',
    overdue: 'Overdue',
    
    // Frequency
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    semiannual: 'Semi-Annual',
    annual: 'Annual',
    adHoc: 'As Needed',
    
    // Asset Types
    electrical: 'Electrical',
    plumbing: 'Plumbing',
    hvac: 'HVAC',
    safety: 'Safety',
    equipment: 'Equipment',
    building: 'Building',
    other: 'Other',
    
    // Maintenance Page
    maintenanceTitle: 'Maintenance System',
    maintenanceSubtitle: 'Comprehensive management of maintenance operations, assets, and vendors',
    maintenanceDashboard: 'Dashboard',
    annualSchedule: 'Annual Schedule',
    maintenanceItems: 'Maintenance Items',
    assets: 'Assets',
    vendors: 'Vendors',
    totalItems: 'Total Items',
    pendingTasks: 'Pending Tasks',
    overdueTasks: 'Overdue Tasks',
    completedThisMonth: 'Completed This Month',
    upcomingMaintenance: 'Upcoming Maintenance',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    deleteItem: 'Delete Item',
    confirmDelete: 'Confirm Delete',
    deleteItemConfirm: 'Are you sure you want to delete this item?',
    itemDeleted: 'Item deleted successfully',
    itemAdded: 'Item added successfully',
    itemUpdated: 'Item updated successfully',
    description: 'Description',
    reminderDays: 'Reminder Days',
    startDate: 'Start Date',
    selectAsset: 'Select Asset',
    selectVendor: 'Select Vendor',
    noAsset: 'No Asset',
    noVendor: 'No Vendor',
    address: 'Address',
    purchaseDate: 'Purchase Date',
    warrantyExpiry: 'Warranty Expiry',
    generateSchedule: 'Generate Schedule',
    maintenanceItem: 'Maintenance Item',
    noMaintenanceItems: 'No maintenance items',
    updateMaintenanceStatus: 'Update Maintenance Status',
    executionDate: 'Execution Date',
    actualCost: 'Actual Cost',
    
    // Offline Mode
    offline: 'Offline',
    syncing: 'Syncing...',
    pendingSync: 'pending sync',
    offlineMessage: 'You are offline. Changes will be saved locally.',
    operationsPending: 'operations pending sync',
    
    // Theme
    toggleTheme: 'Toggle Theme',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    
    // Analytics Page
    analyticsTitle: 'Advanced Analytics',
    analyticsSubtitle: 'Comprehensive overview of declaration system performance',
    declarationTrends: 'Declaration Trends',
    statusAnalysis: 'Status Analysis',
    performanceMetrics: 'Performance Metrics',
    weeklyComparison: 'Weekly Comparison',
    monthlyOverview: 'Monthly Overview',
    yearlyStats: 'Yearly Statistics',
    averageTime: 'Average Processing Time',
    peakHours: 'Peak Activity Hours',
    efficiency: 'Efficiency Rate',
    oneMonth: '1 Month',
    threeMonths: '3 Months',
    sixMonths: '6 Months',
    oneYear: '1 Year',
    refreshData: 'Refresh',
    totalDeclarationsCard: 'Total Declarations',
    completionRateCard: 'Completion Rate',
    avgProcessingDaysCard: 'Avg. Processing Days',
    inProcessingCard: 'In Processing',
    overviewTab: 'Overview',
    trendsTab: 'Trends',
    performanceTab: 'Performance',
    statusDistributionChart: 'Status Distribution',
    statusDistributionDesc: 'Percentage of each status from total declarations',
    typeDistributionChart: 'Type Distribution',
    typeDistributionDesc: 'Comparison between inbound and outbound declarations',
    weeklyActivityChart: 'Weekly Activity',
    weeklyActivityDesc: 'Distribution of declarations by day of week',
    monthlyTrendChart: 'Monthly Trend',
    monthlyTrendDesc: 'Evolution of declaration numbers over months',
    timeDistributionChart: 'Time Distribution',
    timeDistributionDesc: 'Peak hours for creating declarations during the day',
    performanceIndicatorsChart: 'Performance Indicators',
    performanceIndicatorsDesc: 'Percentage of achieving set targets',
    topSendersChart: 'Most Active Senders',
    topSendersDesc: 'Users ranked by number of declarations',
    totalLabel: 'Total',
    completedLabel: 'Completed',
    declarationCount: 'declaration',
    inboundType: 'Inbound',
    outboundType: 'Outbound',
    completionRateMetric: 'Completion Rate',
    processingSpeedMetric: 'Processing Speed',
    efficiencyMetric: 'Efficiency',
    delayed: 'delayed',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    
    // Additional Terms
    selectDate: 'Select Date',
    apply: 'Apply',
    reset: 'Reset',
    more: 'More',
    less: 'Less',
    details: 'Details',
    summary: 'Summary',
    total: 'Total',
    average: 'Average',
    minimum: 'Minimum',
    maximum: 'Maximum',
    count: 'Count',
    percentage: 'Percentage',
    trend: 'Trend',
    growth: 'Growth',
    decline: 'Decline',
    stable: 'Stable',
    
    // Tooltips & Helpers
    clickToView: 'Click to view details',
    clickToEdit: 'Click to edit',
    clickToDelete: 'Click to delete',
    dragToReorder: 'Drag to reorder',
    requiredField: 'This field is required',
    optionalField: 'Optional',
    
    // Notifications
    notifications: 'Notifications',
    newNotification: 'New Notification',
    markRead: 'Mark as Read',
    markAsRead: 'Mark as Read',
    markAllRead: 'Mark All as Read',
    markAllAsRead: 'Mark All as Read',
    allNotificationsRead: 'All notifications marked as read',
    notificationDeleted: 'Notification deleted',
    clearAll: 'Clear All',
    noNotifications: 'No notifications',
    updateFailed: 'Update failed',
    
    // Time
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    lastYear: 'Last Year',
    custom: 'Custom Range',
    
    // Onboarding
    onboardingDashboardTitle: 'Dashboard Overview',
    onboardingDashboardDesc: 'Get a comprehensive view of all your declarations and system statistics at a glance.',
    onboardingDeclarationsTitle: 'Manage Declarations',
    onboardingDeclarationsDesc: 'Create, track, and manage all your declarations with an intuitive workflow.',
    onboardingReportsTitle: 'Reports & Analytics',
    onboardingReportsDesc: 'Generate detailed reports and gain insights from your declaration data.',
    onboardingMaintenanceTitle: 'Maintenance System',
    onboardingMaintenanceDesc: 'Schedule and track maintenance tasks to keep everything running smoothly.',
    onboardingNotificationsTitle: 'Stay Notified',
    onboardingNotificationsDesc: 'Receive real-time notifications about important updates and changes.',
    onboardingSkip: 'Skip',
    onboardingNext: 'Next',
    onboardingPrevious: 'Previous',
    onboardingComplete: 'Get Started',
    
    // 404 Page
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'Oops! The page you are looking for does not exist.',
    returnToHome: 'Return to Home',
    
    // Change Status
    changeStatus: 'Change Status',
    
    // Leave Tracking
    leaveTracking: 'Leave Tracking',
    leaveTrackingSubtitle: 'Track annual leaves, balances, and employee status',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    employeeInformation: 'Employee Information',
    employeeName: 'Employee Name',
    employeeId: 'Employee ID',
    department: 'Department',
    jobTitle: 'Job Title',
    hireDate: 'Hire Date',
    contractType: 'Contract Type',
    employeeContract: 'Employee (Annual)',
    workerContract: 'Worker (Biennial)',
    leaveBalance: 'Leave Balance',
    entitledDays: 'Entitled Days',
    usedDays: 'Used Days',
    remainingBalance: 'Remaining Balance',
    leaveHistory: 'Leave History',
    lastLeaveStart: 'Last Leave Start',
    lastLeaveEnd: 'Last Leave End',
    currentLeave: 'Current Leave',
    currentLeaveStart: 'Current Leave Start',
    currentLeaveEnd: 'Current Leave End',
    expectedReturnDate: 'Expected Return Date',
    actualReturnDate: 'Actual Return Date',
    travelDate: 'Travel Date',
    travelDestination: 'Travel Destination',
    enterNotes: 'Enter notes...',
    recordCreated: 'Record created successfully',
    recordUpdated: 'Record updated successfully',
    recordDeleted: 'Record deleted successfully',
    saveFailed: 'Failed to save record',
    deleteFailed: 'Failed to delete record',
    saving: 'Saving...',
    atWork: 'At Work',
    onLeave: 'On Leave',
    overdueReturn: 'Overdue Return',
    upcomingLeave: 'Upcoming Leave',
    totalEmployees: 'Total Employees',
    currentlyOnLeave: 'Currently On Leave',
    overdueReturns: 'Overdue Returns',
    upcoming30Days: 'Upcoming (30 Days)',
    upcoming60Days: 'Upcoming (60 Days)',
    upcoming90Days: 'Upcoming (90 Days)',
    searchEmployee: 'Search by name, ID, or department...',
    allContracts: 'All Contracts',
    allDepartments: 'All Departments',
    employeeLeaveTracking: 'Employee Leave Tracking',
    noEmployees: 'No employees found',
    noEmployeesDescription: 'Add your first employee to start tracking leaves',
    lastLeave: 'Last Leave',
    nextLeaveDue: 'Next Leave Due',
    returnDate: 'Return Date',
    confirmDeleteEmployee: 'Are you sure you want to delete this employee record?',
    exportAllTracking: 'Export All Tracking',
    exportUpcomingLeaves: 'Export Upcoming Leaves',
    exportOverdueReturns: 'Export Overdue Returns',
    
    // Leave Requests
    leaveRequests: 'Leave Requests',
    leaveRequestsSubtitle: 'Create and manage employee annual leave requests',
    newLeaveRequest: 'New Leave Request',
    annualLeaveRequestForm: 'Annual Leave Request Form',
    requestDetails: 'Request Details',
    leaveStartDate: 'Leave Start Date',
    leaveEndDate: 'Leave End Date',
    daysRequested: 'Days Requested',
    expectedRemainingBalance: 'Expected Remaining Balance',
    leaveReason: 'Leave Reason',
    enterLeaveReason: 'Enter leave reason...',
    deputyInformation: 'Deputy Information',
    deputyName: 'Deputy Name',
    deputyDepartment: 'Deputy Department',
    deputyContact: 'Deputy Contact',
    importantNotice: 'Important Notice',
    leaveWarningMessage: 'Annual leave is granted only after completing 6 months of employment, and the remaining balance must not be less than 5 days after deducting the requested period.',
    submitRequest: 'Submit Request',
    totalRequests: 'Total Requests',
    pendingRequests: 'Pending Requests',
    approvedRequests: 'Approved Requests',
    rejectedRequests: 'Rejected Requests',
    allLeaveRequests: 'All Leave Requests',
    allLeaveRequestsDescription: 'View and manage all submitted leave requests',
    noLeaveRequests: 'No Leave Requests',
    noLeaveRequestsDescription: 'No leave requests have been submitted yet',
    rejectedLessThan6Months: 'Rejected: Less than 6 months',
    rejectedInsufficientBalance: 'Rejected: Insufficient balance',
    originalBalance: 'Original Balance',
    previouslyUsedDays: 'Previously Used Days',
    currentRemainingBalance: 'Current Remaining Balance',
    
    // Bulk Notifications
    bulkNotification: 'Bulk Notification',
    sendBulkNotification: 'Send Bulk Notification',
    notificationTitle: 'Notification Title',
    notificationMessage: 'Notification Message',
    notificationType: 'Notification Type',
    notificationInfo: 'Information',
    notificationSuccess: 'Success',
    notificationWarning: 'Warning',
    notificationError: 'Error',
    relatedDeclarationId: 'Related Declaration ID (Optional)',
    targetUsers: 'Target Users',
    selectAllUsers: 'Select All',
    selectUsersRequired: 'Please select at least one user',
    fillRequiredFields: 'Please fill all required fields',
    notificationsSent: 'notifications sent successfully',
    notificationsSentSuccess: 'Notifications sent successfully',
    notificationsFailed: 'Failed to send notifications',
    sendingNotifications: 'Sending...',
    sendNotifications: 'Send Notifications',
    chooseUsersAndSend: 'Choose users and send notification to all of them',
    failedToLoadUsers: 'Failed to load users list',
    enterNotificationTitle: 'Enter notification title',
    enterNotificationMessage: 'Enter notification message',
    
    // Declaration Details
    archiveFile: 'Archive File',
    selectArchiveFile: 'Select archive file',
    noArchiveFile: 'No archive file',
    archiveFileNotSet: 'Archive file not set',
    senderInfo: 'Sender Information',
    declarationTimeline: 'Declaration Timeline',
    noTimelineHistory: 'No timeline history for this declaration',
    editButton: 'Edit',
    saveButton: 'Save',
    
    // Vendors Management
    vendorUpdatedSuccess: 'Vendor updated successfully',
    vendorAddedSuccess: 'Vendor added successfully',
    vendorDeletedSuccess: 'Vendor deleted successfully',
    confirmDeleteVendor: 'Are you sure you want to delete this vendor?',
    addNewVendor: 'Add New Vendor',
    editVendor: 'Edit Vendor',
    
    // Empty States
    emptyTrashBin: 'Trash bin is empty',
    noDeletedDeclarations: 'No deleted declarations currently',
    noResults: 'No results',
    adjustFiltersForResults: 'Try adjusting filters for other results',
    startByCreatingDeclaration: 'Start by creating a new declaration',
    
    // Petty Cash
    pettyCashTitle: 'Petty Cash Expenses',
    pettyCashSubtitle: 'Manage and track petty cash expenses',
    expenses: 'Expenses',
    costCenters: 'Cost Centers',
    totalExpenses: 'Total Expenses',
    monthlyExpenses: 'Monthly Expenses',
    pendingApproval: 'Pending Approval',
    topCostCenter: 'Top Cost Center',
    topVendor: 'Top Vendor',
    currency: 'SAR',
    addExpense: 'Add Expense',
    editExpense: 'Edit Expense',
    searchExpenses: 'Search expenses...',
    invoiceNumber: 'Invoice Number',
    costCenter: 'Cost Center',
    unitPrice: 'Unit Price',
    expenseApproved: 'Expense approved',
    expenseRejected: 'Expense rejected',
    expenseDeleted: 'Expense deleted',
    expenseAdded: 'Expense added successfully',
    expenseUpdated: 'Expense updated successfully',
    deleteExpenseConfirmation: 'Are you sure you want to delete this expense?',
    noExpensesFound: 'No expenses found',
    selectCostCenter: 'Select cost center',
    invoiceNumberPlaceholder: 'e.g. INV-001',
    vendorPlaceholder: 'Enter vendor name',
    itemNamePlaceholder: 'Enter item name',
    recipientPlaceholder: 'Enter recipient name',
    searchVendor: 'Search vendor',
    applyFilters: 'Apply Filters',
    pettyCashReport: 'Petty Cash Report',
    transactions: 'transactions',
    expensesByCostCenter: 'Expenses by Cost Center',
    expensesDetails: 'Expenses Details',
    costCentersManagement: 'Cost Centers Management',
    addCostCenter: 'Add Cost Center',
    editCostCenter: 'Edit Cost Center',
    nameEn: 'Name (English)',
    nameAr: 'Name (Arabic)',
    costCenterAdded: 'Cost center added',
    costCenterUpdated: 'Cost center updated',
    costCenterDeleted: 'Cost center deleted',
    deleteCostCenterConfirmation: 'Are you sure you want to delete this cost center?',
    noCostCentersFound: 'No cost centers found',
    pettyCash: 'Petty Cash',
    
    // Petty Cash Periods
    pettyCashPeriods: 'Cash Periods',
    openPeriods: 'Open Periods',
    totalBudget: 'Total Budget',
    totalSpent: 'Total Spent',
    openNewPeriod: 'Open New Period',
    periodNumber: 'Period Number',
    responsiblePerson: 'Responsible Person',
    openingBalance: 'Opening Balance',
    expensesCount: 'Expenses Count',
    openedAt: 'Opened At',
    closedAt: 'Closed At',
    periodOpen: 'Open',
    periodClosed: 'Closed',
    closePeriod: 'Close Period',
    openPeriod: 'Open Period',
    closePeriodConfirmTitle: 'Close Petty Cash Period?',
    closePeriodConfirmDescription: 'After closing, no more expenses can be added to this period. It will be sent for approval.',
    periodOpened: 'Period opened successfully',
    periodClosedSuccess: 'Period closed successfully and sent for approval',
    periodApproved: 'Period approved successfully',
    periodRejected: 'Period rejected',
    noPeriodsFound: 'No petty cash periods found',
    openPeriodWarning: 'There is already an open period. Close it before opening a new one.',
    budgetLimit: 'Budget Limit',
    locationPlaceholder: 'e.g. Main Warehouse',
    responsiblePersonPlaceholder: 'Enter responsible person name',
    periodDetails: 'Period Details',
    periodExpenses: 'Period Expenses',
    noExpensesInPeriod: 'No expenses in this period',
    budgetUsage: 'Budget Usage',
    expenseWillBeAddedToPeriod: 'Expense will be added to period',
    noOpenPeriodWarning: 'No open period! You must open a new period before adding expenses.',
    noOpenPeriodError: 'Cannot add expense: No open petty cash period',
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    manage: 'إدارة',
    reports: 'التقارير',
    analytics: 'التحليلات',
    logout: 'تسجيل خروج',
    profile: 'الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    users: 'المستخدمون',
    adminDashboard: 'لوحة المدير',
    managerDashboard: 'لوحة تحكم المدير',
    
    // Login
    welcomeBack: 'مرحباً بعودتك',
    loginSubtitle: 'سجل الدخول للوصول إلى نظام إدارة الإقرارات',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    login: 'تسجيل دخول',
    invalidCredentials: 'بيانات غير صحيحة. يرجى المحاولة مرة أخرى.',
    
    // Dashboard
    systemTitle: 'نظام إدارة الإقرارات',
    streamlineWorkflow: 'بسّط سير عمل الإقرارات',
    streamlineDesc: 'حوّل التتبع اليدوي إلى سير عمل رقمي ذكي مع تحديثات الحالة الفورية والموافقات الآلية والتقارير الشاملة.',
    unsigned: 'غير موقّع',
    pending: 'قيد الانتظار',
    approved: 'موافق عليه',
    archived: 'مؤرشف',
    recentActivity: 'النشاط الأخير',
    quickActions: 'إجراءات سريعة',
    addDeclaration: 'إقرار جديد',
    viewReports: 'عرض التقارير',
    welcome: 'مرحباً',
    all: 'الكل',
    recentDeclarations: 'الإقرارات الحديثة',
    exportAllDeclarations: 'تصدير جميع الإقرارات',
    
    // Admin Dashboard
    adminDashboardTitle: 'لوحة تحكم المدير',
    adminDashboardSubtitle: 'نظرة شاملة على إحصائيات النظام والنشاطات',
    totalUsers: 'إجمالي المستخدمين',
    allSystemAccounts: 'جميع الحسابات المسجلة',
    systemAdmins: 'المسؤولون',
    fullAccess: 'صلاحية كاملة للنظام',
    managers: 'المدراء',
    managerialPermissions: 'صلاحيات إدارية',
    totalDeclarations: 'إجمالي الإقرارات',
    allDeclarations: 'جميع الإقرارات في النظام',
    userDistribution: 'توزيع المستخدمين حسب الصلاحية',
    rolePercentage: 'نسبة كل نوع من الصلاحيات',
    declarationDistribution: 'توزيع حالات الإقرارات',
    countByStage: 'عدد الإقرارات حسب مرحلة سير العمل',
    recentActivities: 'آخر النشاطات',
    latestSystemChanges: 'أحدث التغييرات والتحديثات',
    noRecentActivities: 'لا توجد نشاطات حديثة للعرض',
    statistics: 'الإحصائيات',
    allYears: 'جميع السنوات',
    selectYear: 'اختر السنة',
    userManagement: 'إدارة المستخدمين',
    
    // User Management
    permissionsGuide: 'دليل الصلاحيات',
    systemAdmin: 'مدير النظام',
    subManager: 'مدير',
    regularUser: 'مستخدم عادي',
    usersCount: 'المستخدمون',
    refresh: 'تحديث',
    addUser: 'إضافة مستخدم',
    addNewUser: 'إضافة مستخدم جديد',
    createUserAccount: 'إنشاء حساب مستخدم جديد وتحديد صلاحياته',
    email: 'البريد الإلكتروني',
    role: 'الصلاحية',
    creationDate: 'تاريخ الإنشاء',
    cancel: 'إلغاء',
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    createUser: 'إنشاء المستخدم',
    areYouSure: 'تأكيد الإجراء',
    deleteRoleWarning: 'سيؤدي هذا إلى إزالة صلاحيات المستخدم. لحذف المستخدم بالكامل، استخدم لوحة إدارة قاعدة البيانات.',
    delete: 'حذف',
    deletePermissions: 'إزالة الصلاحيات',
    sendInvitation: 'إرسال الدعوة',
    invitationSent: 'تم إرسال الدعوة بنجاح إلى',
    invitationFailed: 'فشل إرسال الدعوة. يرجى المحاولة مرة أخرى.',
    sending: 'جاري الإرسال...',
    invitationDescription: 'سيتم إرسال بريد دعوة إلى هذا العنوان',
    howItWorks: 'آلية العمل:',
    invitationStep1: 'يتم إرسال بريد الدعوة للمستخدم',
    invitationStep2: 'يضغط المستخدم على رابط التفعيل',
    invitationStep3: 'يقوم بتعيين كلمة المرور الآمنة',
    invitationStep4: 'يمكنه الآن الدخول إلى النظام',
    
    // Permissions
    viewAllDeclarations: 'عرض جميع الإقرارات',
    createEditDeleteDeclarations: 'إنشاء وتعديل وحذف الإقرارات',
    changeAnyDeclarationStatus: 'تحديث حالة أي إقرار',
    manageAllUsers: 'إدارة جميع المستخدمين',
    addDeleteUsers: 'إضافة وإزالة المستخدمين',
    changeUserPermissions: 'تعديل صلاحيات المستخدمين',
    viewReportsStatistics: 'الوصول للتقارير والتحليلات',
    fullSystemAccess: 'صلاحية إدارية كاملة',
    createEditDeclarations: 'إنشاء وتعديل الإقرارات',
    changeAllDeclarationStatus: 'تحديث جميع حالات الإقرارات',
    viewUserInformation: 'عرض معلومات المستخدمين',
    createNewDeclarations: 'إنشاء إقرارات جديدة',
    editOwnDeclarations: 'تعديل إقراراتي فقط',
    changeOwnDeclarationStatus: 'تحديث حالة إقراراتي',
    viewOwnProfile: 'عرض ملفي الشخصي',
    
    // Status Labels
    draft: 'مسودة',
    pendingWarehouseSignature: 'بانتظار التوقيع',
    warehouseSigned: 'موقّع',
    sentToAdminOffice: 'مرسل إلى المكتب',
    receivedByAdminOffice: 'مستلم',
    returnedToWarehouse: 'مُعاد للتعديل',
    returnedForModification: 'مُعاد للتعديل',
    rejected: 'مرفوض',
    pendingSignature: 'بانتظار التوقيع',
    signed: 'موقّع',
    sentToOffice: 'مرسل للمكتب',
    // Dynamic status labels based on declaration type
    pendingDelivererSignature: 'بانتظار توقيع المسلم',
    pendingReceiverSignature: 'بانتظار توقيع المستلم',
    signedByDeliverer: 'موقّع من المسلم',
    signedByReceiver: 'موقّع من المستلم',
    
    // Declaration Details
    declarationDetails: 'تفاصيل الإقرار',
    declarationInfo: 'معلومات الإقرار',
    declarationNumber: 'رقم الإقرار',
    updateStatus: 'تحديث الحالة',
    currentStatus: 'الحالة الحالية',
    timeline: 'المسار الزمني',
    viewTimeline: 'عرض المسار الزمني',
    backToManage: 'العودة للإدارة',
    createdBy: 'أنشئ بواسطة',
    lastUpdated: 'آخر تحديث',
    statusHistory: 'سجل الحالات',
    changedBy: 'تم التغيير بواسطة',
    changedAt: 'وقت التغيير',
    oldStatus: 'الحالة السابقة',
    newStatus: 'الحالة الجديدة',
    notes: 'ملاحظات',
    noNotes: 'لا توجد ملاحظات',
    statusUpdated: 'تم تحديث الحالة بنجاح',
    statusUpdateFailed: 'فشل تحديث الحالة. يرجى المحاولة مرة أخرى.',
    declarationNotFound: 'الإقرار غير موجود',
    
    // Create Declaration
    createDeclaration: 'إنشاء إقرار',
    createNewDeclaration: 'إنشاء إقرار جديد',
    enterDeclarationDetails: 'أدخل تفاصيل الإقرار أدناه',
    declarationNumberLabel: 'رقم الإقرار',
    declarationType: 'النوع',
    selectType: 'اختر النوع',
    entrance: 'دخول',
    exit: 'خروج',
    initialStatus: 'الحالة الأولية',
    selectStatus: 'اختر الحالة',
    declarationCreated: 'تم إنشاء الإقرار بنجاح',
    declarationCreationFailed: 'فشل إنشاء الإقرار. يرجى المحاولة مرة أخرى.',
    numberTooShort: 'رقم الإقرار يجب أن يكون 3 أرقام على الأقل',
    numberTooLong: 'رقم الإقرار طويل جداً',
    numbersOnly: 'يُسمح بالأرقام فقط',
    mustSelectType: 'يرجى اختيار نوع الإقرار',
    mustLogin: 'يتطلب تسجيل الدخول',
    numberExists: 'رقم الإقرار هذا موجود بالفعل',
    
    // Login/Signup
    signup: 'إنشاء حساب',
    createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    signupSuccess: 'تم إنشاء الحساب بنجاح',
    signupFailed: 'فشل إنشاء الحساب. يرجى المحاولة مرة أخرى.',
    enterUsername: 'يرجى إدخال اسم المستخدم',
    loggingIn: 'جاري تسجيل الدخول...',
    creatingAccount: 'جاري إنشاء الحساب...',
    
    // Messages
    success: 'نجح',
    error: 'خطأ',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    loadingData: 'جاري تحميل البيانات...',
    userRoleUpdated: 'تم تحديث صلاحية المستخدم بنجاح',
    userCreatedSuccess: 'تم إنشاء المستخدم بنجاح',
    fillAllFields: 'يرجى ملء جميع الحقول المطلوبة',
    userCreationFailed: 'فشل إنشاء المستخدم. يرجى المحاولة مرة أخرى.',
    permissionsDeleted: 'تم إزالة الصلاحيات بنجاح',
    userDeleted: 'تم حذف المستخدم بنجاح',
    userDeactivated: 'تم تعطيل المستخدم بنجاح',
    userReactivated: 'تم إعادة تفعيل المستخدم بنجاح',
    cannotDeleteSelf: 'لا يمكنك حذف حسابك الخاص',
    notAuthorizedToDelete: 'غير مصرح لك بحذف المستخدمين',
    cannotDeleteUserLinkedData: 'لا يمكن حذف مستخدم لديه بيانات مرتبطة',
    cannotDeleteUser: 'لا يمكن حذف المستخدم',
    userHasLinkedDataDescription: 'هذا المستخدم لديه بيانات مرتبطة في النظام ولا يمكن حذفه نهائياً. يمكنك تعطيل المستخدم بدلاً من ذلك.',
    linkedDataSummary: 'البيانات المرتبطة',
    items: 'عناصر',
    alternativeAction: 'إجراء بديل',
    deactivateUserDescription: 'تعطيل المستخدم سيمنعه من تسجيل الدخول مع الحفاظ على جميع بياناته. يمكن إعادة تفعيله لاحقاً إذا لزم الأمر.',
    deactivateUser: 'تعطيل المستخدم',
    reactivateUser: 'إعادة تفعيل المستخدم',
    showInactiveUsers: 'عرض المستخدمين المعطلين',
    confirmDeleteUser: 'تأكيد حذف المستخدم',
    deleteUserWarning: 'هل أنت متأكد من رغبتك في حذف هذا المستخدم نهائياً؟',
    deleteUserPermanentWarning: 'هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع بيانات المستخدم نهائياً.',
    deleteUser: 'حذف المستخدم',
    you: 'أنت',
    
    // Dashboard Specific
    dashboardSubtitle: 'تتبع وإدارة جميع إقراراتك في مكان واحد',
    manageUsers: 'إدارة المستخدمين',
    viewAll: 'عرض الكل',
    noDeclarations: 'لا توجد إقرارات',
    
    // Manage Page
    manageDeclarations: 'إدارة الإقرارات',
    manageSubtitle: 'عرض وفلترة وإدارة جميع إقرارات النظام',
    searchPlaceholder: 'البحث برقم الإقرار أو المرسل...',
    filterBySender: 'تصفية حسب المرسل',
    allSenders: 'جميع المرسلين',
    filterByDate: 'تصفية حسب التاريخ',
    dateRange: 'نطاق التاريخ',
    from: 'من',
    to: 'إلى',
    clearFilters: 'مسح الفلاتر',
    selectAll: 'تحديد الكل',
    selected: 'محدد',
    exportSelected: 'تصدير المحدد',
    deleteSelected: 'حذف المحدد',
    noDeclarationsFound: 'لم يتم العثور على إقرارات',
    tryAdjustingFilters: 'جرب تعديل فلاتر البحث',
    bulkExport: 'التصدير الجماعي',
    
    // Reports Page
    reportsTitle: 'التقارير والتحليلات',
    reportsSubtitle: 'تحليل شامل للإقرارات وأداء النظام',
    exportOptions: 'خيارات التصدير',
    statusBreakdown: 'تفصيل الحالات',
    declarationsOverTime: 'الإقرارات عبر الوقت',
    topUsers: 'أكثر المساهمين',
    by: 'بواسطة',
    
    // Profile Page
    myProfile: 'ملفي الشخصي',
    personalInformation: 'المعلومات الشخصية',
    accountSettings: 'إعدادات الحساب',
    securitySettings: 'إعدادات الأمان',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    updatePassword: 'تحديث كلمة المرور',
    passwordUpdated: 'تم تحديث كلمة المرور بنجاح',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    saveChanges: 'حفظ التغييرات',
    profileSubtitle: 'إدارة معلوماتك الشخصية وإعدادات الحساب',
    accountRole: 'صلاحية الحساب',
    personalData: 'البيانات الشخصية',
    usernameLabel: 'اسم المستخدم',
    emailLabel: 'البريد الإلكتروني',
    jobRole: 'الدور الوظيفي',
    resetFields: 'إعادة تعيين',
    saveProfile: 'حفظ التعديلات',
    savingProfile: 'جاري الحفظ...',
    profileUpdated: 'تم تحديث بياناتك الشخصية بنجاح',
    profileUpdateFailed: 'فشل تحديث البيانات',
    usernameAlreadyTaken: 'اسم المستخدم مستخدم بالفعل',
    emailAlreadyTaken: 'البريد الإلكتروني مستخدم بالفعل',
    dataValidationError: 'خطأ في البيانات',
    changePasswordTitle: 'تغيير كلمة المرور',
    newPasswordLabel: 'كلمة المرور الجديدة',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    passwordMinLength: '10 أحرف على الأقل',
    passwordUppercase: 'حرف كبير واحد على الأقل',
    passwordLowercase: 'حرف صغير واحد على الأقل',
    passwordNumber: 'رقم واحد على الأقل',
    passwordSpecialChar: 'رمز خاص واحد على الأقل (!@#$%^&*)',
    passwordStrength: 'قوة كلمة المرور',
    passwordRequirements: 'متطلبات كلمة المرور',
    weak: 'ضعيفة',
    medium: 'متوسطة',
    strong: 'قوية',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',
    usernameHint: '2-50 حرف، حروف وأرقام وشرطات سفلية',
    pleaseWait: 'الرجاء الانتظار...',
    skipToContent: 'تخطي إلى المحتوى الرئيسي',
    invalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    invalidData: 'البيانات المدخلة غير صحيحة',
    passwordChangeFailed: 'فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.',
    passwordChangeSuccess: 'تم تغيير كلمة المرور بنجاح',
    
    // Common Actions
    view: 'عرض',
    edit: 'تعديل',
    export: 'تصدير',
    import: 'استيراد',
    print: 'طباعة',
    close: 'إغلاق',
    save: 'حفظ',
    update: 'تحديث',
    confirm: 'تأكيد',
    
    // Manage
    declarations: 'الإقرارات',
    search: 'بحث',
    filter: 'فلتر',
    status: 'الحالة',
    allStatuses: 'جميع الحالات',
    declarationId: 'رقم الإقرار',
    type: 'النوع',
    sender: 'المرسل',
    createdDate: 'تاريخ الإنشاء',
    actions: 'الإجراءات',
    bulkActions: 'إجراءات جماعية',
    showing: 'عرض',
    of: 'من',
    results: 'نتيجة',
    
    // Reports
    reportsAnalytics: 'التقارير والتحليلات',
    overview: 'نظرة عامة',
    statusDistribution: 'توزيع الحالات',
    userActivity: 'نشاط المستخدمين',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportCSV: 'تصدير CSV',
    monthlyTrends: 'الاتجاهات الشهرية',
    completionRate: 'معدل الإنجاز',
    avgProcessingTime: 'متوسط المعالجة',
    days: 'أيام',
    savedFilters: 'الفلاتر المحفوظة',
    noSavedFilters: 'لا توجد فلاتر محفوظة',
    saveCurrentFilter: 'حفظ الفلتر الحالي',
    saveFilter: 'حفظ الفلتر',
    saveFilterDescription: 'احفظ إعدادات الفلتر للوصول السريع',
    filterNamePlaceholder: 'اسم الفلتر...',
    filterSaved: 'تم حفظ الفلتر بنجاح',
    filterDeleted: 'تم حذف الفلتر',
    filterApplied: 'تم تطبيق الفلتر',
    enterFilterName: 'يرجى إدخال اسم الفلتر',
    exportSuccess: 'تم تصدير التقرير بنجاح',
    changedDeclarationStatus: 'قام بتغيير حالة الإقرار',
    userLabel: 'مستخدم',
    switchLanguage: 'تبديل اللغة',
    
    // Navigation
    home: 'الرئيسية',
    maintenance: 'الصيانة',
    installApp: 'تثبيت التطبيق',
    auditLog: 'سجل التدقيق',
    checkingUpdates: 'جاري التحقق من التحديثات',
    noUpdates: 'لا توجد تحديثات',
    updateAvailable: 'تحديث متاح',
    pageWillReload: 'سيتم إعادة تحميل الصفحة لتطبيق التحديث...',
    youUsingLatest: 'أنت تستخدم أحدث إصدار',
    serviceWorkerNotRegistered: 'Service Worker غير مسجل',
    notSupported: 'غير مدعوم',
    browserNotSupport: 'متصفحك لا يدعم هذه الميزة',
    updateCheckFailed: 'فشل التحقق من التحديثات',
    forceUpdate: 'تحديث الآن',
    forceUpdateDescription: 'سيتم مسح جميع البيانات المؤقتة وإعادة تحميل أحدث نسخة من النظام. هل أنت متأكد؟',
    updateInProgress: 'جاري التحديث...',
    updateNow: 'تحديث الآن',
    currentVersion: 'الإصدار الحالي',
    newDesktopVersionAvailable: 'يوجد إصدار جديد من تطبيق سطح المكتب',
    downloadUpdate: 'تحميل التحديث',
    later: 'لاحقاً',

    // Holiday Attendance
    holidayAttendance: 'كشف دوام العطلات',
    holidayAttendanceDesc: 'إدارة كشوفات دوام الموظفين والعمال خلال العطل الرسمية',
    newSheet: 'كشف جديد',
    totalSheets: 'إجمالي الكشوفات',
    noSheetsFound: 'لا توجد كشوفات',
    sheetDetails: 'تفاصيل الكشف',
    sheetInfo: 'بيانات الكشف',
    workRecords: 'سجلات العمل',
    employeesData: 'بيانات الموظفين',
    warehouseName: 'اسم المخزن',
    warehouseNumber: 'رقم المخزن',
    holidayName: 'اسم العطلة الرسمية',
    periodStart: 'من تاريخ',
    periodEnd: 'إلى تاريخ',
    monthYear: 'الشهر / السنة',
    monthYearPlaceholder: 'مثال: مارس 2026م',
    sheetCreated: 'تم إنشاء الكشف بنجاح',
    sheetUpdated: 'تم تحديث الكشف بنجاح',
    saveSheetFirst: 'يرجى حفظ الكشف أولاً',
    addRecord: 'إضافة سجل',
    workType: 'نوع العمل',
    workDate: 'تاريخ العمل',
    presentEmployees: 'الموظف المتواجد أثناء العمل',
    enterEmployeeNames: 'أدخل أسماء الموظفين...',
    noRecords: 'لا توجد سجلات بعد',
    totalWorkDays: 'إجمالي أيام العمل',
    deleteSheet: 'حذف الكشف',
    deleteSheetConfirm: 'هل أنت متأكد من حذف هذا الكشف؟',
    deleteRecord: 'حذف السجل',
    deleteRecordConfirm: 'هل أنت متأكد من حذف هذا السجل؟',
    deleteEmployeeConfirm: 'هل أنت متأكد من حذف هذا الموظف؟',
    printPreview: 'معاينة الطباعة',
    serial: 'المسلسل',

    // Archive Files
    archiveFiles: 'ملفات الأرشيف',
    archiveFilesManagement: 'إدارة ملفات الأرشيف',
    addArchiveFile: 'إضافة ملف أرشيف',
    archiveNumber: 'رقم الأرشيف',
    archiveDescription: 'الوصف',
    declarationsCount: 'عدد الإقرارات',
    createdAt: 'تاريخ الإنشاء',
    noArchiveFiles: 'لا توجد ملفات أرشيف',
    addFirstArchiveFile: 'أنشئ أول ملف أرشيف',
    enterArchiveNumber: 'أدخل رقم الأرشيف',
    enterDescription: 'أدخل الوصف (اختياري)',
    add: 'إضافة',
    adding: 'جاري الإضافة...',
    archiveFileAdded: 'تم إنشاء ملف الأرشيف بنجاح',
    archiveFileDeleted: 'تم حذف ملف الأرشيف بنجاح',
    archiveFileExists: 'رقم الأرشيف هذا موجود بالفعل',
    cannotDeleteArchive: 'لا يمكن حذف أرشيف مرتبط بإقرارات',
    confirmDeleteArchive: 'هل أنت متأكد من حذف ملف الأرشيف هذا؟',
    unknown: 'غير معروف',
    noRecentDeclarations: 'لا توجد إقرارات حديثة',
    
    // Manage Page Extended
    trashBin: 'سلة المحذوفات',
    allSendersFilter: 'جميع المرسلين',
    exportExcelBtn: 'تصدير إلى Excel',
    exportPDFBtn: 'تصدير إلى PDF',
    manageArchiveFiles: 'إدارة ملفات الأرشيف والإقرارات',
    movedToTrash: 'تم نقل الإقرار إلى سلة المحذوفات',
    alreadyDeleted: 'الإقرار محذوف بالفعل',
    
    // Maintenance
    maintenanceSystem: 'نظام الصيانة',
    itemName: 'اسم العنصر',
    frequency: 'التكرار',
    lastMaintenance: 'آخر صيانة',
    nextMaintenance: 'الصيانة القادمة',
    estimatedCost: 'التكلفة المقدرة',
    active: 'نشط',
    inactive: 'غير نشط',
    viewDetails: 'عرض التفاصيل',
    addMaintenanceItem: 'إضافة عنصر صيانة',
    addAsset: 'إضافة أصل',
    addVendor: 'إضافة مورد',
    assetName: 'اسم الأصل',
    vendorName: 'اسم المورد',
    contactPerson: 'جهة الاتصال',
    contactInfo: 'معلومات الاتصال',
    specialization: 'التخصص',
    location: 'الموقع',
    site: 'المنشأة',
    code: 'الرمز',
    phone: 'الهاتف',
    
    // Maintenance Status
    done: 'تم',
    notRequired: 'غير مطلوب',
    overdue: 'متأخر',
    
    // Frequency
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    semiannual: 'نصف سنوي',
    annual: 'سنوي',
    adHoc: 'عند الحاجة',
    
    // Asset Types
    electrical: 'كهربائي',
    plumbing: 'سباكة',
    hvac: 'تكييف',
    safety: 'أمان',
    equipment: 'معدات',
    building: 'مبنى',
    other: 'أخرى',
    
    // Maintenance Page
    maintenanceTitle: 'نظام الصيانة الدورية',
    maintenanceSubtitle: 'إدارة شاملة لعمليات الصيانة والأصول والموردين',
    maintenanceDashboard: 'لوحة التحكم',
    annualSchedule: 'الجدول السنوي',
    maintenanceItems: 'بنود الصيانة',
    assets: 'الأصول',
    vendors: 'الموردين',
    totalItems: 'إجمالي البنود',
    pendingTasks: 'المهام المعلقة',
    overdueTasks: 'المهام المتأخرة',
    completedThisMonth: 'المكتملة هذا الشهر',
    upcomingMaintenance: 'الصيانة القادمة',
    addItem: 'إضافة بند',
    editItem: 'تعديل البند',
    deleteItem: 'حذف البند',
    confirmDelete: 'تأكيد الحذف',
    deleteItemConfirm: 'هل أنت متأكد من حذف هذا البند؟',
    itemDeleted: 'تم حذف البند بنجاح',
    itemAdded: 'تم إضافة البند بنجاح',
    itemUpdated: 'تم تحديث البند بنجاح',
    description: 'الوصف',
    reminderDays: 'أيام التذكير',
    startDate: 'تاريخ البدء',
    selectAsset: 'اختر الأصل',
    selectVendor: 'اختر المورد',
    noAsset: 'بدون أصل',
    noVendor: 'بدون مورد',
    address: 'العنوان',
    generateSchedule: 'توليد الجدول',
    maintenanceItem: 'بند الصيانة',
    noMaintenanceItems: 'لا توجد بنود صيانة',
    updateMaintenanceStatus: 'تحديث حالة الصيانة',
    executionDate: 'تاريخ التنفيذ',
    actualCost: 'التكلفة الفعلية',
    purchaseDate: 'تاريخ الشراء',
    warrantyExpiry: 'انتهاء الضمان',
    
    // Offline Mode
    offline: 'غير متصل',
    syncing: 'جاري المزامنة...',
    pendingSync: 'عملية معلقة',
    offlineMessage: 'أنت غير متصل بالإنترنت. التغييرات ستُحفظ محلياً.',
    operationsPending: 'عملية في انتظار المزامنة',
    
    // Theme
    toggleTheme: 'تبديل السمة',
    lightMode: 'فاتح',
    darkMode: 'داكن',
    systemMode: 'النظام',
    
    // Analytics Page
    analyticsTitle: 'تحليلات متقدمة',
    analyticsSubtitle: 'رؤية شاملة لأداء نظام الإقرارات',
    declarationTrends: 'اتجاهات الإقرارات',
    statusAnalysis: 'تحليل الحالات',
    performanceMetrics: 'مقاييس الأداء',
    weeklyComparison: 'المقارنة الأسبوعية',
    monthlyOverview: 'النظرة الشهرية',
    yearlyStats: 'إحصائيات سنوية',
    averageTime: 'متوسط وقت المعالجة',
    peakHours: 'ساعات الذروة',
    efficiency: 'معدل الكفاءة',
    oneMonth: 'شهر واحد',
    threeMonths: '3 أشهر',
    sixMonths: '6 أشهر',
    oneYear: 'سنة',
    refreshData: 'تحديث',
    totalDeclarationsCard: 'إجمالي الإقرارات',
    completionRateCard: 'معدل الإنجاز',
    avgProcessingDaysCard: 'متوسط أيام المعالجة',
    inProcessingCard: 'قيد المعالجة',
    overviewTab: 'نظرة عامة',
    trendsTab: 'الاتجاهات',
    performanceTab: 'الأداء',
    statusDistributionChart: 'توزيع الحالات',
    statusDistributionDesc: 'نسبة كل حالة من إجمالي الإقرارات',
    typeDistributionChart: 'توزيع الأنواع',
    typeDistributionDesc: 'مقارنة بين إقرارات الدخول والخروج',
    weeklyActivityChart: 'النشاط الأسبوعي',
    weeklyActivityDesc: 'توزيع الإقرارات حسب أيام الأسبوع',
    monthlyTrendChart: 'الاتجاه الشهري',
    monthlyTrendDesc: 'تطور أعداد الإقرارات على مدار الأشهر',
    timeDistributionChart: 'التوزيع الزمني',
    timeDistributionDesc: 'أوقات الذروة لإنشاء الإقرارات خلال اليوم',
    performanceIndicatorsChart: 'مؤشرات الأداء',
    performanceIndicatorsDesc: 'نسبة تحقيق الأهداف المحددة',
    topSendersChart: 'أكثر المرسلين نشاطاً',
    topSendersDesc: 'ترتيب المستخدمين حسب عدد الإقرارات',
    totalLabel: 'الإجمالي',
    completedLabel: 'مكتملة',
    declarationCount: 'إقرار',
    inboundType: 'دخول',
    outboundType: 'خروج',
    completionRateMetric: 'معدل الإنجاز',
    processingSpeedMetric: 'سرعة المعالجة',
    efficiencyMetric: 'الكفاءة',
    delayed: 'متأخر',
    sunday: 'الأحد',
    monday: 'الإثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    
    // Additional Terms
    selectDate: 'اختر التاريخ',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    more: 'المزيد',
    less: 'أقل',
    details: 'التفاصيل',
    summary: 'ملخص',
    total: 'الإجمالي',
    average: 'المتوسط',
    minimum: 'الأدنى',
    maximum: 'الأقصى',
    count: 'العدد',
    percentage: 'النسبة',
    trend: 'الاتجاه',
    growth: 'نمو',
    decline: 'انخفاض',
    stable: 'مستقر',
    
    // Tooltips & Helpers
    clickToView: 'انقر لعرض التفاصيل',
    clickToEdit: 'انقر للتعديل',
    clickToDelete: 'انقر للحذف',
    dragToReorder: 'اسحب لإعادة الترتيب',
    requiredField: 'هذا الحقل مطلوب',
    optionalField: 'اختياري',
    
    // Notifications
    notifications: 'الإشعارات',
    newNotification: 'إشعار جديد',
    markRead: 'تحديد كمقروء',
    markAsRead: 'تحديد كمقروء',
    markAllRead: 'تحديد الكل كمقروء',
    markAllAsRead: 'تحديد الكل كمقروء',
    allNotificationsRead: 'تم تحديد جميع الإشعارات كمقروءة',
    notificationDeleted: 'تم حذف الإشعار',
    clearAll: 'مسح الكل',
    noNotifications: 'لا توجد إشعارات',
    updateFailed: 'فشل التحديث',
    
    // Time
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisYear: 'هذه السنة',
    lastWeek: 'الأسبوع الماضي',
    lastMonth: 'الشهر الماضي',
    lastYear: 'السنة الماضية',
    custom: 'نطاق مخصص',
    
    // Onboarding
    onboardingDashboardTitle: 'نظرة عامة على لوحة التحكم',
    onboardingDashboardDesc: 'احصل على نظرة شاملة لجميع إقراراتك وإحصائيات النظام في لمحة واحدة.',
    onboardingDeclarationsTitle: 'إدارة الإقرارات',
    onboardingDeclarationsDesc: 'أنشئ وتتبع وأدر جميع إقراراتك بسير عمل سلس.',
    onboardingReportsTitle: 'التقارير والتحليلات',
    onboardingReportsDesc: 'أنشئ تقارير مفصلة واحصل على رؤى من بيانات إقراراتك.',
    onboardingMaintenanceTitle: 'نظام الصيانة',
    onboardingMaintenanceDesc: 'جدول وتتبع مهام الصيانة للحفاظ على سير العمل بسلاسة.',
    onboardingNotificationsTitle: 'البقاء على اطلاع',
    onboardingNotificationsDesc: 'استلم إشعارات فورية حول التحديثات والتغييرات المهمة.',
    onboardingSkip: 'تخطي',
    onboardingNext: 'التالي',
    onboardingPrevious: 'السابق',
    onboardingComplete: 'ابدأ الآن',
    
    // 404 Page
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundDesc: 'عذراً! الصفحة التي تبحث عنها غير موجودة.',
    returnToHome: 'العودة للرئيسية',
    
    // Change Status
    changeStatus: 'تغيير الحالة',
    
    // Leave Tracking
    leaveTracking: 'متابعة الإجازات',
    leaveTrackingSubtitle: 'متابعة الإجازات السنوية وأرصدة وحالة الموظفين',
    addEmployee: 'إضافة موظف',
    editEmployee: 'تعديل موظف',
    employeeInformation: 'بيانات الموظف',
    employeeName: 'اسم الموظف',
    employeeId: 'الرقم الوظيفي',
    department: 'الإدارة',
    jobTitle: 'المسمى الوظيفي',
    hireDate: 'تاريخ التعيين',
    contractType: 'نوع العقد',
    employeeContract: 'موظف (سنوي)',
    workerContract: 'عامل (كل سنتين)',
    leaveBalance: 'رصيد الإجازة',
    entitledDays: 'الأيام المستحقة',
    usedDays: 'الأيام المستخدمة',
    remainingBalance: 'الرصيد المتبقي',
    leaveHistory: 'سجل الإجازات',
    lastLeaveStart: 'بداية آخر إجازة',
    lastLeaveEnd: 'نهاية آخر إجازة',
    currentLeave: 'الإجازة الحالية',
    currentLeaveStart: 'بداية الإجازة الحالية',
    currentLeaveEnd: 'نهاية الإجازة الحالية',
    expectedReturnDate: 'تاريخ العودة المتوقع',
    actualReturnDate: 'تاريخ العودة الفعلي',
    travelDate: 'تاريخ السفر',
    travelDestination: 'وجهة السفر',
    enterNotes: 'أدخل ملاحظات...',
    recordCreated: 'تم إنشاء السجل بنجاح',
    recordUpdated: 'تم تحديث السجل بنجاح',
    recordDeleted: 'تم حذف السجل بنجاح',
    saveFailed: 'فشل في حفظ السجل',
    deleteFailed: 'فشل في حذف السجل',
    saving: 'جاري الحفظ...',
    atWork: 'على رأس العمل',
    onLeave: 'في إجازة',
    overdueReturn: 'متأخر عن العودة',
    upcomingLeave: 'إجازة قادمة',
    totalEmployees: 'إجمالي الموظفين',
    currentlyOnLeave: 'في إجازة حالياً',
    overdueReturns: 'متأخرين عن العودة',
    upcoming30Days: 'قادمة (30 يوم)',
    upcoming60Days: 'قادمة (60 يوم)',
    upcoming90Days: 'قادمة (90 يوم)',
    searchEmployee: 'بحث بالاسم أو الرقم أو الإدارة...',
    allContracts: 'جميع العقود',
    allDepartments: 'جميع الإدارات',
    employeeLeaveTracking: 'متابعة إجازات الموظفين',
    noEmployees: 'لا يوجد موظفين',
    noEmployeesDescription: 'أضف أول موظف لبدء متابعة الإجازات',
    lastLeave: 'آخر إجازة',
    nextLeaveDue: 'الإجازة القادمة',
    returnDate: 'تاريخ العودة',
    confirmDeleteEmployee: 'هل أنت متأكد من حذف سجل هذا الموظف؟',
    exportAllTracking: 'تصدير كل المتابعة',
    exportUpcomingLeaves: 'تصدير الإجازات القادمة',
    exportOverdueReturns: 'تصدير المتأخرين عن العودة',
    
    // Leave Requests
    leaveRequests: 'طلبات الإجازة',
    leaveRequestsSubtitle: 'إنشاء وإدارة طلبات الإجازة السنوية للموظفين',
    newLeaveRequest: 'طلب إجازة جديد',
    annualLeaveRequestForm: 'نموذج طلب إجازة سنوية',
    requestDetails: 'تفاصيل الطلب',
    leaveStartDate: 'تاريخ بداية الإجازة',
    leaveEndDate: 'تاريخ نهاية الإجازة',
    daysRequested: 'الأيام المطلوبة',
    expectedRemainingBalance: 'الرصيد المتبقي المتوقع',
    leaveReason: 'سبب الإجازة',
    enterLeaveReason: 'أدخل سبب الإجازة...',
    deputyInformation: 'معلومات النائب',
    deputyName: 'اسم النائب',
    deputyDepartment: 'إدارة النائب',
    deputyContact: 'رقم تواصل النائب',
    importantNotice: 'ملاحظة مهمة',
    leaveWarningMessage: 'لا تُمنح الإجازة السنوية إلا بعد إتمام 6 أشهر من العمل، ويجب ألا يقل الرصيد المتبقي عن 5 أيام بعد خصم الفترة المطلوبة.',
    submitRequest: 'تقديم الطلب',
    totalRequests: 'إجمالي الطلبات',
    pendingRequests: 'طلبات معلقة',
    approvedRequests: 'طلبات موافق عليها',
    rejectedRequests: 'طلبات مرفوضة',
    allLeaveRequests: 'جميع طلبات الإجازة',
    allLeaveRequestsDescription: 'عرض وإدارة جميع طلبات الإجازة المقدمة',
    noLeaveRequests: 'لا توجد طلبات إجازة',
    noLeaveRequestsDescription: 'لم يتم تقديم أي طلبات إجازة حتى الآن',
    rejectedLessThan6Months: 'مرفوض: أقل من 6 أشهر',
    rejectedInsufficientBalance: 'مرفوض: رصيد غير كافي',
    originalBalance: 'الرصيد الأصلي',
    previouslyUsedDays: 'الأيام المستخدمة سابقاً',
    currentRemainingBalance: 'الرصيد المتبقي الحالي',
    
    // Bulk Notifications
    bulkNotification: 'إشعار جماعي',
    sendBulkNotification: 'إرسال إشعار جماعي',
    notificationTitle: 'عنوان الإشعار',
    notificationMessage: 'نص الإشعار',
    notificationType: 'نوع الإشعار',
    notificationInfo: 'معلومة',
    notificationSuccess: 'نجاح',
    notificationWarning: 'تحذير',
    notificationError: 'خطأ',
    relatedDeclarationId: 'رقم الإقرار المرتبط (اختياري)',
    targetUsers: 'المستخدمون المستهدفون',
    selectAllUsers: 'تحديد الكل',
    selectUsersRequired: 'يجب اختيار مستخدم واحد على الأقل',
    fillRequiredFields: 'يجب ملء جميع الحقول المطلوبة',
    notificationsSent: 'إشعار تم إرساله بنجاح',
    notificationsSentSuccess: 'تم إرسال الإشعارات بنجاح',
    notificationsFailed: 'فشل إرسال الإشعارات',
    sendingNotifications: 'جاري الإرسال...',
    sendNotifications: 'إرسال الإشعارات',
    chooseUsersAndSend: 'اختر المستخدمين وأرسل إشعار لهم جميعاً',
    failedToLoadUsers: 'فشل تحميل قائمة المستخدمين',
    enterNotificationTitle: 'أدخل عنوان الإشعار',
    enterNotificationMessage: 'أدخل نص الإشعار',
    
    // Declaration Details
    archiveFile: 'ملف الأرشفة',
    selectArchiveFile: 'اختر ملف الأرشفة',
    noArchiveFile: 'بدون ملف أرشفة',
    archiveFileNotSet: 'لم يتم تحديد ملف أرشفة',
    senderInfo: 'معلومات المرسل',
    declarationTimeline: 'الخط الزمني للإقرار',
    noTimelineHistory: 'لا يوجد سجل تغييرات لهذا الإقرار',
    editButton: 'تعديل',
    saveButton: 'حفظ',
    
    // Vendors Management
    vendorUpdatedSuccess: 'تم تحديث المورد بنجاح',
    vendorAddedSuccess: 'تم إضافة المورد بنجاح',
    vendorDeletedSuccess: 'تم حذف المورد بنجاح',
    confirmDeleteVendor: 'هل أنت متأكد من حذف هذا المورد؟',
    addNewVendor: 'إضافة مورد جديد',
    editVendor: 'تعديل المورد',
    
    // Empty States
    emptyTrashBin: 'سلة المحذوفات فارغة',
    noDeletedDeclarations: 'لا توجد إقرارات محذوفة حالياً',
    noResults: 'لا توجد نتائج',
    adjustFiltersForResults: 'جرب تعديل الفلاتر للحصول على نتائج أخرى',
    startByCreatingDeclaration: 'ابدأ بإنشاء إقرار جديد',
    
    // Petty Cash
    pettyCashTitle: 'المصاريف النثرية',
    pettyCashSubtitle: 'إدارة ومتابعة المصاريف النثرية',
    expenses: 'المصاريف',
    costCenters: 'مراكز التكلفة',
    totalExpenses: 'إجمالي المصاريف',
    monthlyExpenses: 'مصاريف الشهر',
    pendingApproval: 'بانتظار الاعتماد',
    topCostCenter: 'أعلى مركز تكلفة',
    topVendor: 'أكثر مورد',
    currency: 'ريال',
    addExpense: 'إضافة مصروف',
    editExpense: 'تعديل المصروف',
    searchExpenses: 'البحث في المصاريف...',
    invoiceNumber: 'رقم الفاتورة',
    costCenter: 'مركز التكلفة',
    unitPrice: 'سعر الوحدة',
    expenseApproved: 'تم اعتماد المصروف',
    expenseRejected: 'تم رفض المصروف',
    expenseDeleted: 'تم حذف المصروف',
    expenseAdded: 'تم إضافة المصروف بنجاح',
    expenseUpdated: 'تم تحديث المصروف بنجاح',
    deleteExpenseConfirmation: 'هل أنت متأكد من حذف هذا المصروف؟',
    noExpensesFound: 'لا توجد مصاريف',
    selectCostCenter: 'اختر مركز التكلفة',
    invoiceNumberPlaceholder: 'مثال: INV-001',
    vendorPlaceholder: 'أدخل اسم المورد',
    itemNamePlaceholder: 'أدخل اسم الصنف',
    recipientPlaceholder: 'أدخل اسم المستلم',
    searchVendor: 'بحث عن مورد',
    applyFilters: 'تطبيق الفلاتر',
    pettyCashReport: 'تقرير المصاريف النثرية',
    transactions: 'معاملة',
    expensesByCostCenter: 'المصاريف حسب مركز التكلفة',
    expensesDetails: 'تفاصيل المصاريف',
    costCentersManagement: 'إدارة مراكز التكلفة',
    addCostCenter: 'إضافة مركز تكلفة',
    editCostCenter: 'تعديل مركز التكلفة',
    nameEn: 'الاسم (إنجليزي)',
    nameAr: 'الاسم (عربي)',
    costCenterAdded: 'تم إضافة مركز التكلفة',
    costCenterUpdated: 'تم تحديث مركز التكلفة',
    costCenterDeleted: 'تم حذف مركز التكلفة',
    deleteCostCenterConfirmation: 'هل أنت متأكد من حذف مركز التكلفة هذا؟',
    noCostCentersFound: 'لا توجد مراكز تكلفة',
    pettyCash: 'المصاريف النثرية',
    
    // Petty Cash Periods
    pettyCashPeriods: 'فترات النثرية',
    openPeriods: 'الفترات المفتوحة',
    totalBudget: 'إجمالي الميزانية',
    totalSpent: 'إجمالي المصروف',
    openNewPeriod: 'فتح نثرية جديدة',
    periodNumber: 'رقم النثرية',
    responsiblePerson: 'المسؤول',
    openingBalance: 'الرصيد الافتتاحي',
    expensesCount: 'عدد المصروفات',
    openedAt: 'تاريخ الفتح',
    closedAt: 'تاريخ الإغلاق',
    periodOpen: 'مفتوحة',
    periodClosed: 'مغلقة',
    closePeriod: 'إغلاق النثرية',
    openPeriod: 'فتح النثرية',
    closePeriodConfirmTitle: 'إغلاق النثرية؟',
    closePeriodConfirmDescription: 'بعد الإغلاق، لن يمكن إضافة مصروفات جديدة لهذه النثرية. سيتم إرسالها للاعتماد.',
    periodOpened: 'تم فتح النثرية بنجاح',
    periodClosedSuccess: 'تم إغلاق النثرية وإرسالها للاعتماد',
    periodApproved: 'تم اعتماد النثرية بنجاح',
    periodRejected: 'تم رفض النثرية',
    noPeriodsFound: 'لا توجد فترات نثرية',
    openPeriodWarning: 'يوجد نثرية مفتوحة بالفعل. يجب إغلاقها قبل فتح نثرية جديدة.',
    budgetLimit: 'سقف الميزانية',
    locationPlaceholder: 'مثال: المخزن الرئيسي',
    responsiblePersonPlaceholder: 'أدخل اسم المسؤول',
    periodDetails: 'تفاصيل النثرية',
    periodExpenses: 'مصروفات النثرية',
    noExpensesInPeriod: 'لا توجد مصروفات في هذه النثرية',
    budgetUsage: 'نسبة الاستهلاك',
    expenseWillBeAddedToPeriod: 'سيتم إضافة المصروف للنثرية',
    noOpenPeriodWarning: 'لا توجد نثرية مفتوحة! يجب فتح نثرية جديدة قبل إضافة المصروفات.',
    noOpenPeriodError: 'لا يمكن إضافة مصروف: لا توجد نثرية مفتوحة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'ar';
  });

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'en' ? 'ar' : 'en';
      localStorage.setItem('app-language', newLang);
      
      // Update HTML attributes immediately without reload
      document.documentElement.lang = newLang;
      document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
      
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  // Set initial HTML attributes - centralized RTL handling
  useEffect(() => {
    const isRTL = language === 'ar';
    const htmlElement = document.documentElement;
    const bodyElement = document.body;
    
    // Set direction on html and body
    htmlElement.lang = language;
    htmlElement.dir = isRTL ? 'rtl' : 'ltr';
    bodyElement.dir = isRTL ? 'rtl' : 'ltr';
    
    // Add/remove RTL class for CSS targeting
    if (isRTL) {
      htmlElement.classList.add('rtl');
      htmlElement.classList.remove('ltr');
      bodyElement.style.textAlign = 'right';
    } else {
      htmlElement.classList.add('ltr');
      htmlElement.classList.remove('rtl');
      bodyElement.style.textAlign = 'left';
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div 
        dir={language === 'ar' ? 'rtl' : 'ltr'} 
        className="font-sans"
        style={{ 
          direction: language === 'ar' ? 'rtl' : 'ltr',
          textAlign: language === 'ar' ? 'right' : 'left'
        }}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
