import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    manage: 'Manage',
    reports: 'Reports',
    analytics: 'Analytics',
    logout: 'Sign Out',
    profile: 'Profile',
    changePassword: 'Change Password',
    users: 'Users',
    adminDashboard: 'Admin Panel',
    
    // Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to access your declaration management system',
    username: 'Username',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    login: 'Sign In',
    invalidCredentials: 'Invalid credentials. Please try again.',
    
    // Dashboard
    systemTitle: 'Declaration Management System',
    streamlineWorkflow: 'Streamline Your Declaration Workflow',
    streamlineDesc: 'Transform manual tracking into intelligent digital workflows with real-time status updates, automated approvals, and comprehensive reporting.',
    unsigned: 'Unsigned',
    pending: 'Pending',
    approved: 'Approved',
    archived: 'Archived',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    addDeclaration: 'New Declaration',
    viewReports: 'View Reports',
    welcome: 'Welcome',
    all: 'All',
    recentDeclarations: 'Recent Declarations',
    exportAllDeclarations: 'Export All Declarations',
    exportToExcel: 'Export to Excel',
    exportToPDF: 'Export to PDF',
    exportedSuccessfully: 'Exported successfully',
    noDataToExport: 'No data to export',
    declarationsReport: 'Declarations Report',
    virtualScrolling: 'Virtual Scrolling',
    virtualScrollingHint: 'Enable for better performance with large datasets',
    
    // Admin Dashboard
    adminDashboardTitle: 'Admin Panel',
    adminDashboardSubtitle: 'Comprehensive overview of system statistics and activities',
    totalUsers: 'Total Users',
    allSystemAccounts: 'All registered accounts',
    systemAdmins: 'Administrators',
    fullAccess: 'Full system access',
    managers: 'Managers',
    managerialPermissions: 'Managerial permissions',
    totalDeclarations: 'Total Declarations',
    allDeclarations: 'All declarations in system',
    userDistribution: 'User Distribution by Role',
    rolePercentage: 'Percentage breakdown by role type',
    declarationDistribution: 'Declaration Status Distribution',
    countByStage: 'Count of declarations by workflow stage',
    recentActivities: 'Recent Activities',
    latestSystemChanges: 'Latest system changes and updates',
    noRecentActivities: 'No recent activities to display',
    statistics: 'Statistics',
    userManagement: 'User Management',
    
    // User Management
    permissionsGuide: 'Permissions Guide',
    systemAdmin: 'Administrator',
    subManager: 'Manager',
    regularUser: 'Standard User',
    usersCount: 'Users',
    refresh: 'Refresh',
    addUser: 'Add User',
    addNewUser: 'Add New User',
    createUserAccount: 'Create a new user account and assign permissions',
    email: 'Email Address',
    role: 'Role',
    creationDate: 'Created On',
    cancel: 'Cancel',
    create: 'Create',
    creating: 'Creating...',
    createUser: 'Create User',
    areYouSure: 'Confirm Action',
    deleteRoleWarning: 'This will remove the user\'s permissions. To completely delete the user, access the database administration panel.',
    delete: 'Delete',
    deletePermissions: 'Remove Permissions',
    sendInvitation: 'Send Invitation',
    invitationSent: 'Invitation sent successfully to',
    invitationFailed: 'Failed to send invitation. Please try again.',
    sending: 'Sending...',
    invitationDescription: 'An invitation email will be sent to this address',
    howItWorks: 'How it works:',
    invitationStep1: 'Invitation email is sent to the user',
    invitationStep2: 'User clicks the activation link',
    invitationStep3: 'User sets their secure password',
    invitationStep4: 'User can now access the system',
    
    // Permissions
    viewAllDeclarations: 'View all declarations',
    createEditDeleteDeclarations: 'Create, edit, and delete declarations',
    changeAnyDeclarationStatus: 'Update any declaration status',
    manageAllUsers: 'Manage all users',
    addDeleteUsers: 'Add and remove users',
    changeUserPermissions: 'Modify user permissions',
    viewReportsStatistics: 'Access reports and analytics',
    fullSystemAccess: 'Full administrative access',
    createEditDeclarations: 'Create and edit declarations',
    changeAllDeclarationStatus: 'Update all declaration statuses',
    viewUserInformation: 'View user information',
    createNewDeclarations: 'Create new declarations',
    editOwnDeclarations: 'Edit own declarations only',
    changeOwnDeclarationStatus: 'Update own declaration status',
    viewOwnProfile: 'View personal profile',
    
    // Status Labels
    draft: 'Draft',
    pendingWarehouseSignature: 'Awaiting Signature',
    warehouseSigned: 'Signed',
    sentToAdminOffice: 'Sent to Admin',
    receivedByAdminOffice: 'Received',
    returnedToWarehouse: 'Returned',
    rejected: 'Rejected',
    
    // Declaration Details
    declarationDetails: 'Declaration Details',
    declarationInfo: 'Declaration Information',
    declarationNumber: 'Declaration ID',
    updateStatus: 'Update Status',
    currentStatus: 'Current Status',
    timeline: 'Timeline',
    viewTimeline: 'View Timeline',
    backToManage: 'Back to Manage',
    createdBy: 'Created By',
    lastUpdated: 'Last Updated',
    statusHistory: 'Status History',
    changedBy: 'Changed By',
    changedAt: 'Changed At',
    oldStatus: 'Previous Status',
    newStatus: 'New Status',
    notes: 'Notes',
    noNotes: 'No notes available',
    statusUpdated: 'Status updated successfully',
    statusUpdateFailed: 'Failed to update status. Please try again.',
    declarationNotFound: 'Declaration not found',
    
    // Create Declaration
    createDeclaration: 'Create Declaration',
    createNewDeclaration: 'Create New Declaration',
    enterDeclarationDetails: 'Enter declaration details below',
    declarationNumberLabel: 'Declaration ID',
    declarationType: 'Type',
    selectType: 'Select Type',
    entrance: 'Inbound',
    exit: 'Outbound',
    initialStatus: 'Initial Status',
    selectStatus: 'Select Status',
    declarationCreated: 'Declaration created successfully',
    declarationCreationFailed: 'Failed to create declaration. Please try again.',
    numberTooShort: 'Declaration ID must be at least 3 digits',
    numberTooLong: 'Declaration ID is too long',
    numbersOnly: 'Only numeric characters allowed',
    mustSelectType: 'Please select a declaration type',
    mustLogin: 'Authentication required',
    numberExists: 'This Declaration ID already exists',
    
    // Login/Signup
    signup: 'Sign Up',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signupSuccess: 'Account created successfully',
    signupFailed: 'Account creation failed. Please try again.',
    enterUsername: 'Please enter your username',
    loggingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    
    // Messages
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    noData: 'No data available',
    loadingData: 'Loading data...',
    userRoleUpdated: 'User role updated successfully',
    userCreatedSuccess: 'User created successfully',
    fillAllFields: 'Please complete all required fields',
    userCreationFailed: 'User creation failed. Please try again.',
    permissionsDeleted: 'Permissions removed successfully',
    
    // Dashboard Specific
    dashboardSubtitle: 'Track and manage all your declarations in one place',
    manageUsers: 'Manage Users',
    viewAll: 'View All',
    noDeclarations: 'No declarations found',
    
    // Manage Page
    manageDeclarations: 'Manage Declarations',
    manageSubtitle: 'View, filter, and manage all system declarations',
    searchPlaceholder: 'Search by ID or sender...',
    filterBySender: 'Filter by Sender',
    allSenders: 'All Senders',
    filterByDate: 'Filter by Date',
    dateRange: 'Date Range',
    from: 'From',
    to: 'To',
    clearFilters: 'Clear Filters',
    selectAll: 'Select All',
    selected: 'selected',
    exportSelected: 'Export Selected',
    deleteSelected: 'Delete Selected',
    noDeclarationsFound: 'No declarations found',
    tryAdjustingFilters: 'Try adjusting your search filters',
    bulkExport: 'Bulk Export',
    
    // Keyboard navigation
    keyboardShortcuts: 'Keyboard shortcuts',
    navigateRows: 'Navigate rows',
    viewDetailsKey: 'View details',
    selectRow: 'Select row',
    expandRow: 'Expand row',
    deleteRow: 'Delete row',
    
    // Reports Page
    reportsTitle: 'Reports & Analytics',
    reportsSubtitle: 'Comprehensive analysis of declarations and system performance',
    exportOptions: 'Export Options',
    statusBreakdown: 'Status Breakdown',
    declarationsOverTime: 'Declarations Over Time',
    topUsers: 'Top Contributors',
    by: 'by',
    
    // Profile Page
    myProfile: 'My Profile',
    personalInformation: 'Personal Information',
    accountSettings: 'Account Settings',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated successfully',
    passwordMismatch: 'Passwords do not match',
    saveChanges: 'Save Changes',
    profileSubtitle: 'Manage your personal information and account settings',
    accountRole: 'Account Role',
    passwordMinLength: 'At least 10 characters',
    passwordUppercase: 'At least one uppercase letter',
    passwordLowercase: 'At least one lowercase letter',
    passwordNumber: 'At least one number',
    passwordSpecialChar: 'At least one special character (!@#$%^&*)',
    passwordStrength: 'Password strength',
    passwordRequirements: 'Password requirements',
    requirements: 'requirements',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    usernameHint: '2-50 characters, letters, numbers, underscores',
    pleaseWait: 'Please wait...',
    skipToContent: 'Skip to main content',
    invalidEmail: 'Invalid email address',
    invalidData: 'Invalid data entered',
    passwordChangeFailed: 'Failed to change password. Please try again.',
    passwordChangeSuccess: 'Password changed successfully',
    
    // Common Actions
    view: 'View',
    edit: 'Edit',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    close: 'Close',
    save: 'Save',
    update: 'Update',
    confirm: 'Confirm',
    
    // Manage
    declarations: 'Declarations',
    search: 'Search',
    filter: 'Filter',
    status: 'Status',
    allStatuses: 'All Statuses',
    declarationId: 'Declaration ID',
    type: 'Type',
    sender: 'Sender',
    createdDate: 'Created Date',
    actions: 'Actions',
    bulkActions: 'Bulk Actions',
    changeStatusTo: 'Change status to...',
    bulkStatusChanged: 'Status changed',
    bulkDeleted: 'Items moved to trash',
    confirmBulkDelete: 'Confirm Bulk Delete',
    bulkDeleteWarning: 'Are you sure you want to delete {count} declarations? They will be moved to trash.',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    showing: 'Showing',
    of: 'of',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    overview: 'Overview',
    statusDistribution: 'Status Distribution',
    userActivity: 'User Activity',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    exportCSV: 'Export CSV',
    monthlyTrends: 'Monthly Trends',
    completionRate: 'Completion Rate',
    avgProcessingTime: 'Avg. Processing',
    days: 'days',
    savedFilters: 'Saved Filters',
    noSavedFilters: 'No saved filters',
    saveCurrentFilter: 'Save current filter',
    saveFilter: 'Save Filter',
    saveFilterDescription: 'Save your current filter settings for quick access',
    filterNamePlaceholder: 'Filter name...',
    filterSaved: 'Filter saved successfully',
    filterDeleted: 'Filter deleted',
    filterApplied: 'Filter applied',
    enterFilterName: 'Please enter a filter name',
    exportSuccess: 'Report exported successfully',
    changedDeclarationStatus: 'changed declaration status',
    userLabel: 'User',
    switchLanguage: 'Switch Language',
    
    // Navigation
    home: 'Home',
    maintenance: 'Maintenance',
    installApp: 'Install App',
    auditLog: 'Audit Log',
    checkingUpdates: 'Checking for updates',
    noUpdates: 'No updates available',
    updateAvailable: 'Update available',
    pageWillReload: 'Page will reload to apply update...',
    youUsingLatest: 'You are using the latest version',
    serviceWorkerNotRegistered: 'Service Worker not registered',
    notSupported: 'Not supported',
    browserNotSupport: 'Your browser does not support this feature',
    updateCheckFailed: 'Failed to check for updates',
    forceUpdate: 'Update Now',
    
    // Archive Files
    archiveFiles: 'Archive Files',
    archiveFilesManagement: 'Archive File Management',
    addArchiveFile: 'Add Archive File',
    archiveNumber: 'Archive Number',
    archiveDescription: 'Description',
    declarationsCount: 'Declaration Count',
    createdAt: 'Created At',
    noArchiveFiles: 'No archive files found',
    addFirstArchiveFile: 'Create your first archive file',
    enterArchiveNumber: 'Enter archive number',
    enterDescription: 'Enter description (optional)',
    add: 'Add',
    adding: 'Adding...',
    archiveFileAdded: 'Archive file created successfully',
    archiveFileDeleted: 'Archive file deleted successfully',
    archiveFileExists: 'This archive number already exists',
    cannotDeleteArchive: 'Cannot delete archive with linked declarations',
    confirmDeleteArchive: 'Are you sure you want to delete this archive file?',
    unknown: 'Unknown',
    noRecentDeclarations: 'No recent declarations',
    
    // Trash
    trashBin: 'Trash',
    deletedDate: 'Deleted Date',
    daysRemaining: 'Days Remaining',
    trashEmpty: 'Trash is empty',
    noDeletedDeclarations: 'No deleted declarations currently',
    trashInfo: 'Important information about trash:',
    trashRestore: 'Deleted declarations can be restored within 30 days',
    trashAutoDelete: 'After 30 days, declarations will be permanently deleted',
    restore: 'Restore',
    permanentDelete: 'Permanently delete',
    noActivitiesInPeriod: 'No activities in the selected period',
    startCreating: 'No declarations created yet. Start by creating a new one.',
    
    // Manage Page Extended
    allSendersFilter: 'All Senders',
    exportExcelBtn: 'Export to Excel',
    exportPDFBtn: 'Export to PDF',
    manageArchiveFiles: 'Manage archive files and declarations',
    movedToTrash: 'Declaration moved to trash',
    alreadyDeleted: 'Declaration already deleted',
    
    // Maintenance
    maintenanceSystem: 'Maintenance System',
    itemName: 'Item Name',
    frequency: 'Frequency',
    lastMaintenance: 'Last Maintenance',
    nextMaintenance: 'Next Maintenance',
    estimatedCost: 'Estimated Cost',
    active: 'Active',
    inactive: 'Inactive',
    viewDetails: 'View Details',
    addMaintenanceItem: 'Add Maintenance Item',
    addAsset: 'Add Asset',
    addVendor: 'Add Vendor',
    assetName: 'Asset Name',
    vendorName: 'Vendor Name',
    contactPerson: 'Contact Person',
    contactInfo: 'Contact Information',
    specialization: 'Specialization',
    location: 'Location',
    site: 'Site',
    code: 'Code',
    phone: 'Phone',
    
    // Maintenance Status
    done: 'Completed',
    notRequired: 'Not Required',
    overdue: 'Overdue',
    
    // Frequency
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    semiannual: 'Semi-Annual',
    annual: 'Annual',
    adHoc: 'As Needed',
    
    // Asset Types
    electrical: 'Electrical',
    plumbing: 'Plumbing',
    hvac: 'HVAC',
    safety: 'Safety',
    equipment: 'Equipment',
    building: 'Building',
    other: 'Other',
    
    // Maintenance Page
    maintenanceTitle: 'Maintenance System',
    maintenanceSubtitle: 'Comprehensive management of maintenance operations, assets, and vendors',
    maintenanceDashboard: 'Dashboard',
    annualSchedule: 'Annual Schedule',
    maintenanceItems: 'Maintenance Items',
    assets: 'Assets',
    vendors: 'Vendors',
    totalItems: 'Total Items',
    pendingTasks: 'Pending Tasks',
    overdueTasks: 'Overdue Tasks',
    completedThisMonth: 'Completed This Month',
    upcomingMaintenance: 'Upcoming Maintenance',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    deleteItem: 'Delete Item',
    confirmDelete: 'Confirm Delete',
    deleteItemConfirm: 'Are you sure you want to delete this item?',
    itemDeleted: 'Item deleted successfully',
    itemAdded: 'Item added successfully',
    itemUpdated: 'Item updated successfully',
    description: 'Description',
    reminderDays: 'Reminder Days',
    startDate: 'Start Date',
    selectAsset: 'Select Asset',
    selectVendor: 'Select Vendor',
    noAsset: 'No Asset',
    noVendor: 'No Vendor',
    address: 'Address',
    purchaseDate: 'Purchase Date',
    warrantyExpiry: 'Warranty Expiry',
    
    // Offline Mode
    offline: 'Offline',
    syncing: 'Syncing...',
    pendingSync: 'pending sync',
    offlineMessage: 'You are offline. Changes will be saved locally.',
    operationsPending: 'operations pending sync',
    
    // Theme
    toggleTheme: 'Toggle Theme',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    
    // Analytics Page
    analyticsTitle: 'Advanced Analytics',
    analyticsSubtitle: 'Comprehensive overview of declaration system performance',
    declarationTrends: 'Declaration Trends',
    statusAnalysis: 'Status Analysis',
    performanceMetrics: 'Performance Metrics',
    weeklyComparison: 'Weekly Comparison',
    monthlyOverview: 'Monthly Overview',
    yearlyStats: 'Yearly Statistics',
    averageTime: 'Average Processing Time',
    peakHours: 'Peak Activity Hours',
    efficiency: 'Efficiency Rate',
    oneMonth: '1 Month',
    threeMonths: '3 Months',
    sixMonths: '6 Months',
    oneYear: '1 Year',
    refreshData: 'Refresh',
    totalDeclarationsCard: 'Total Declarations',
    completionRateCard: 'Completion Rate',
    avgProcessingDaysCard: 'Avg. Processing Days',
    inProcessingCard: 'In Processing',
    overviewTab: 'Overview',
    trendsTab: 'Trends',
    performanceTab: 'Performance',
    statusDistributionChart: 'Status Distribution',
    statusDistributionDesc: 'Percentage of each status from total declarations',
    typeDistributionChart: 'Type Distribution',
    typeDistributionDesc: 'Comparison between inbound and outbound declarations',
    weeklyActivityChart: 'Weekly Activity',
    weeklyActivityDesc: 'Distribution of declarations by day of week',
    monthlyTrendChart: 'Monthly Trend',
    monthlyTrendDesc: 'Evolution of declaration numbers over months',
    timeDistributionChart: 'Time Distribution',
    timeDistributionDesc: 'Peak hours for creating declarations during the day',
    performanceIndicatorsChart: 'Performance Indicators',
    performanceIndicatorsDesc: 'Percentage of achieving set targets',
    topSendersChart: 'Most Active Senders',
    topSendersDesc: 'Users ranked by number of declarations',
    totalLabel: 'Total',
    completedLabel: 'Completed',
    declarationCount: 'declaration',
    inboundType: 'Inbound',
    outboundType: 'Outbound',
    completionRateMetric: 'Completion Rate',
    processingSpeedMetric: 'Processing Speed',
    efficiencyMetric: 'Efficiency',
    delayed: 'delayed',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    
    // Additional Terms
    selectDate: 'Select Date',
    apply: 'Apply',
    reset: 'Reset',
    more: 'More',
    less: 'Less',
    details: 'Details',
    summary: 'Summary',
    total: 'Total',
    average: 'Average',
    minimum: 'Minimum',
    maximum: 'Maximum',
    count: 'Count',
    percentage: 'Percentage',
    trend: 'Trend',
    growth: 'Growth',
    decline: 'Decline',
    stable: 'Stable',
    
    // Tooltips & Helpers
    clickToView: 'Click to view details',
    clickToEdit: 'Click to edit',
    clickToDelete: 'Click to delete',
    dragToReorder: 'Drag to reorder',
    requiredField: 'This field is required',
    optionalField: 'Optional',
    
    // Notifications
    newNotification: 'New Notification',
    markAsRead: 'Mark as Read',
    markAllAsRead: 'Mark All as Read',
    clearAll: 'Clear All',
    noNotifications: 'No notifications',
    
    // Time
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    lastYear: 'Last Year',
    custom: 'Custom Range',
    
    // Onboarding
    onboardingDashboardTitle: 'Dashboard Overview',
    onboardingDashboardDesc: 'Get a comprehensive view of all your declarations and system statistics at a glance.',
    onboardingDeclarationsTitle: 'Manage Declarations',
    onboardingDeclarationsDesc: 'Create, track, and manage all your declarations with an intuitive workflow.',
    onboardingReportsTitle: 'Reports & Analytics',
    onboardingReportsDesc: 'Generate detailed reports and gain insights from your declaration data.',
    onboardingMaintenanceTitle: 'Maintenance System',
    onboardingMaintenanceDesc: 'Schedule and track maintenance tasks to keep everything running smoothly.',
    onboardingNotificationsTitle: 'Stay Notified',
    onboardingNotificationsDesc: 'Receive real-time notifications about important updates and changes.',
    onboardingSkip: 'Skip',
    onboardingNext: 'Next',
    onboardingPrevious: 'Previous',
    onboardingComplete: 'Get Started',
    
    // 404 Page
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'Oops! The page you are looking for does not exist.',
    returnToHome: 'Return to Home',
    
    // Change Status
    changeStatus: 'Change Status',
    
    // Reports & Analytics Tabs (new keys only)
    exportTab: 'Export',
    adminStatsTab: 'Admin Stats',
    
    // Pagination
    rowsPerPage: 'Rows per page',
    firstPage: 'First page',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    lastPage: 'Last page',
    page: 'Page',
    
    // Dashboard Charts
    quickStatsOverview: 'Quick Stats Overview',
    declarationBreakdown: 'Breakdown of declarations by status',
    
    // Date range presets
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last90Days: 'Last 90 Days',
    
    // Dashboard Actions
    declarationRestored: 'Declaration restored successfully',
    declarationPermanentlyDeleted: 'Declaration permanently deleted',
    permanentDeleteWarning: '⚠️ Warning: This declaration will be permanently deleted and cannot be recovered. Are you sure?',
    
    // Profile Page Extended
    personalData: 'Personal Information',
    usernameLabel: 'Username',
    emailLabel: 'Email',
    functionalRole: 'Job Role',
    resetChanges: 'Reset',
    saving: 'Saving...',
    saveEdits: 'Save Changes',
    changePasswordTitle: 'Change Password',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    updatingPassword: 'Updating...',
    updatePasswordBtn: 'Update Password',
    dataUpdated: 'Profile updated successfully',
    usernameTaken: 'Username is already taken',
    emailTaken: 'Email is already taken',
    dataUpdateFailed: 'Failed to update profile',
    profileDataError: 'Invalid profile data',
    passwordsNotMatch: 'Passwords do not match',
    
    // Maintenance Extended
    maintenanceItemsTitle: 'Maintenance Items Management',
    maintenanceItemsDesc: 'Define recurring tasks and requirements',
    addNewItem: 'Add New Item',
    editMaintenanceItem: 'Edit Maintenance Item',
    addMaintenanceItemTitle: 'Add New Maintenance Item',
    itemNameLabel: 'Item Name',
    itemNamePlaceholder: 'e.g. Air Conditioner Maintenance - First Floor',
    linkedAsset: 'Linked Asset',
    selectAssetPlaceholder: 'Select Asset',
    noAssetOption: 'No Asset',
    executingParty: 'Executing Vendor',
    selectVendorPlaceholder: 'Select Vendor',
    noVendorOption: 'No Vendor',
    repetition: 'Frequency',
    startDateLabel: 'Start Date',
    estimatedCostLabel: 'Estimated Cost',
    reminderBeforeDays: 'Reminder (Days Before)',
    descriptionLabel: 'Description',
    notesLabel: 'Notes',
    activeItem: 'Active Item',
    itemUpdatedSuccess: 'Item updated successfully',
    itemAddedSuccess: 'Item added successfully',
    scheduleGeneratedSuccess: 'Item added and annual schedule generated successfully',
    confirmDeleteItem: 'Are you sure you want to delete this item? All linked schedules will be deleted.',
    itemDeletedSuccess: 'Item deleted successfully',
    
    // Assets Extended
    assetsTitle: 'Assets & Equipment Management',
    assetsDesc: 'Register and track assets and equipment',
    addNewAsset: 'Add New Asset',
    editAssetTitle: 'Edit Asset',
    addAssetTitle: 'Add New Asset',
    assetNameLabel: 'Asset Name',
    codeLabel: 'Code',
    typeLabel: 'Type',
    locationLabel: 'Location',
    siteLabel: 'Site',
    purchaseDateLabel: 'Purchase Date',
    warrantyExpiryLabel: 'Warranty Expiry',
    activeAsset: 'Active Asset',
    assetUpdatedSuccess: 'Asset updated successfully',
    assetAddedSuccess: 'Asset added successfully',
    confirmDeleteAsset: 'Are you sure you want to delete this asset?',
    assetDeletedSuccess: 'Asset deleted successfully',
    
    // Vendors Extended
    vendorsTitle: 'Vendors & Maintenance Companies',
    vendorsDesc: 'Add and edit vendor information',
    addNewVendor: 'Add New Vendor',
    editVendorTitle: 'Edit Vendor',
    addVendorTitle: 'Add New Vendor',
    vendorNameLabel: 'Vendor Name',
    responsiblePerson: 'Contact Person',
    phoneLabel: 'Phone',
    emailFieldLabel: 'Email',
    addressLabel: 'Address',
    specializationLabel: 'Specialization',
    specializationPlaceholder: 'e.g. Electrical, Plumbing, HVAC',
    activeVendor: 'Active Vendor',
    vendorUpdatedSuccess: 'Vendor updated successfully',
    vendorAddedSuccess: 'Vendor added successfully',
    confirmDeleteVendor: 'Are you sure you want to delete this vendor?',
    vendorDeletedSuccess: 'Vendor deleted successfully',
    
    // Audit Logs
    auditLogsTitle: 'Audit Logs',
    auditLogsDesc: 'Comprehensive log of all important system operations',
    totalLogs: 'Total Logs',
    createOperations: 'Create Operations',
    updateOperations: 'Update Operations',
    deleteOperations: 'Delete Operations',
    searchByIdOrUser: 'Search by ID or user...',
    operationType: 'Operation Type',
    allOperations: 'All Operations',
    createAction: 'Create',
    updateAction: 'Update',
    deleteAction: 'Delete',
    assignRole: 'Assign Role',
    updateRole: 'Update Role',
    removeRole: 'Remove Role',
    tableFilter: 'Table',
    allTables: 'All Tables',
    declarationsTable: 'Declarations',
    userRolesTable: 'User Roles',
    maintenanceItemsTable: 'Maintenance Items',
    maintenanceScheduleTable: 'Maintenance Schedule',
    logsTableTitle: 'Logs',
    dateTimeColumn: 'Date & Time',
    userColumn: 'User',
    operationColumn: 'Operation',
    tableColumn: 'Table',
    idColumn: 'ID',
    unauthorized: 'Unauthorized',
    adminOnlyPage: 'This page is available for administrators only',
    unknownUser: 'Unknown',
    failedLoginAttempt: 'Failed Login',
    
    // Declaration Details Page
    backToDashboard: 'Back to Dashboard',
    declarationDetailsTitle: 'Declaration Details',
    detailsTab: 'Details',
    timelineTab: 'Timeline',
    coreInfo: 'Core Information',
    declarationTypeLabel: 'Declaration Type',
    statusLabel: 'Status',
    createdDateLabel: 'Created Date',
    lastUpdateLabel: 'Last Update',
    archiveFileLabel: 'Archive File',
    selectArchiveFile: 'Select archive file',
    noArchiveFile: 'No archive file',
    editBtn: 'Edit',
    saveBtn: 'Save',
    cancelBtn: 'Cancel',
    senderInfo: 'Sender Information',
    usernameColumn: 'Username',
    emailColumn: 'Email',
    declarationTimeline: 'Declaration Timeline',
    noHistoryRecords: 'No history records for this declaration',
    declarationNotExist: 'Declaration does not exist',
    archiveFileUpdated: 'Archive file updated',
    archiveFileUpdateFailed: 'Failed to update archive file',
    statusUpdateSuccess: 'Declaration status updated',
    statusUpdateError: 'Failed to update status',
    
    // Status Labels Full
    statusDraft: 'Draft',
    statusPendingWarehouseSignature: 'Awaiting Warehouse Signature',
    statusWarehouseSigned: 'Signed by Warehouse',
    statusSentToAdminOffice: 'Sent to Admin Office',
    statusReceivedByAdminOffice: 'Received by Admin Office',
    statusReturnedToWarehouse: 'Returned to Warehouse for Archiving',
    statusArchived: 'Archived',
    statusRejected: 'Rejected / Needs Correction',
    
    // Forgot Password Page
    forgotPasswordTitle: 'Forgot Password?',
    forgotPasswordDesc: 'Enter your email and we will send you a password reset link',
    emailAddress: 'Email Address',
    sendResetLink: 'Send Reset Link',
    sendingResetLink: 'Sending...',
    resetLinkSent: 'Sent Successfully',
    resetLinkSentDesc: 'Check your email to reset your password',
    resetLinkFailed: 'Failed to send reset email',
    backToLogin: 'Back to Login',
    
    // Reset Password Page
    invalidResetLink: 'Invalid or expired link',
    
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    manage: 'إدارة',
    reports: 'التقارير',
    analytics: 'التحليلات',
    logout: 'تسجيل خروج',
    profile: 'الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    users: 'المستخدمون',
    adminDashboard: 'لوحة المدير',
    
    // Login
    welcomeBack: 'مرحباً بعودتك',
    loginSubtitle: 'سجل الدخول للوصول إلى نظام إدارة الإقرارات',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    login: 'تسجيل دخول',
    invalidCredentials: 'بيانات غير صحيحة. يرجى المحاولة مرة أخرى.',
    
    // Dashboard
    systemTitle: 'نظام إدارة الإقرارات',
    streamlineWorkflow: 'بسّط سير عمل الإقرارات',
    streamlineDesc: 'حوّل التتبع اليدوي إلى سير عمل رقمي ذكي مع تحديثات الحالة الفورية والموافقات الآلية والتقارير الشاملة.',
    unsigned: 'غير موقّع',
    pending: 'قيد الانتظار',
    approved: 'موافق عليه',
    archived: 'مؤرشف',
    recentActivity: 'النشاط الأخير',
    quickActions: 'إجراءات سريعة',
    addDeclaration: 'إقرار جديد',
    viewReports: 'عرض التقارير',
    welcome: 'مرحباً',
    all: 'الكل',
    recentDeclarations: 'الإقرارات الحديثة',
    exportAllDeclarations: 'تصدير جميع الإقرارات',
    exportToExcel: 'تصدير إلى Excel',
    exportToPDF: 'تصدير إلى PDF',
    exportedSuccessfully: 'تم التصدير بنجاح',
    noDataToExport: 'لا توجد بيانات للتصدير',
    declarationsReport: 'تقرير الإقرارات',
    virtualScrolling: 'التمرير الافتراضي',
    virtualScrollingHint: 'تفعيل لأداء أفضل مع البيانات الكبيرة',
    
    // Admin Dashboard
    adminDashboardTitle: 'لوحة تحكم المدير',
    adminDashboardSubtitle: 'نظرة شاملة على إحصائيات النظام والنشاطات',
    totalUsers: 'إجمالي المستخدمين',
    allSystemAccounts: 'جميع الحسابات المسجلة',
    systemAdmins: 'المسؤولون',
    fullAccess: 'صلاحية كاملة للنظام',
    managers: 'المدراء',
    managerialPermissions: 'صلاحيات إدارية',
    totalDeclarations: 'إجمالي الإقرارات',
    allDeclarations: 'جميع الإقرارات في النظام',
    userDistribution: 'توزيع المستخدمين حسب الصلاحية',
    rolePercentage: 'نسبة كل نوع من الصلاحيات',
    declarationDistribution: 'توزيع حالات الإقرارات',
    countByStage: 'عدد الإقرارات حسب مرحلة سير العمل',
    recentActivities: 'آخر النشاطات',
    latestSystemChanges: 'أحدث التغييرات والتحديثات',
    noRecentActivities: 'لا توجد نشاطات حديثة للعرض',
    statistics: 'الإحصائيات',
    userManagement: 'إدارة المستخدمين',
    
    // User Management
    permissionsGuide: 'دليل الصلاحيات',
    systemAdmin: 'مدير النظام',
    subManager: 'مدير',
    regularUser: 'مستخدم عادي',
    usersCount: 'المستخدمون',
    refresh: 'تحديث',
    addUser: 'إضافة مستخدم',
    addNewUser: 'إضافة مستخدم جديد',
    createUserAccount: 'إنشاء حساب مستخدم جديد وتحديد صلاحياته',
    email: 'البريد الإلكتروني',
    role: 'الصلاحية',
    creationDate: 'تاريخ الإنشاء',
    cancel: 'إلغاء',
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    createUser: 'إنشاء المستخدم',
    areYouSure: 'تأكيد الإجراء',
    deleteRoleWarning: 'سيؤدي هذا إلى إزالة صلاحيات المستخدم. لحذف المستخدم بالكامل، استخدم لوحة إدارة قاعدة البيانات.',
    delete: 'حذف',
    deletePermissions: 'إزالة الصلاحيات',
    sendInvitation: 'إرسال الدعوة',
    invitationSent: 'تم إرسال الدعوة بنجاح إلى',
    invitationFailed: 'فشل إرسال الدعوة. يرجى المحاولة مرة أخرى.',
    sending: 'جاري الإرسال...',
    invitationDescription: 'سيتم إرسال بريد دعوة إلى هذا العنوان',
    howItWorks: 'آلية العمل:',
    invitationStep1: 'يتم إرسال بريد الدعوة للمستخدم',
    invitationStep2: 'يضغط المستخدم على رابط التفعيل',
    invitationStep3: 'يقوم بتعيين كلمة المرور الآمنة',
    invitationStep4: 'يمكنه الآن الدخول إلى النظام',
    
    // Permissions
    viewAllDeclarations: 'عرض جميع الإقرارات',
    createEditDeleteDeclarations: 'إنشاء وتعديل وحذف الإقرارات',
    changeAnyDeclarationStatus: 'تحديث حالة أي إقرار',
    manageAllUsers: 'إدارة جميع المستخدمين',
    addDeleteUsers: 'إضافة وإزالة المستخدمين',
    changeUserPermissions: 'تعديل صلاحيات المستخدمين',
    viewReportsStatistics: 'الوصول للتقارير والتحليلات',
    fullSystemAccess: 'صلاحية إدارية كاملة',
    createEditDeclarations: 'إنشاء وتعديل الإقرارات',
    changeAllDeclarationStatus: 'تحديث جميع حالات الإقرارات',
    viewUserInformation: 'عرض معلومات المستخدمين',
    createNewDeclarations: 'إنشاء إقرارات جديدة',
    editOwnDeclarations: 'تعديل إقراراتي فقط',
    changeOwnDeclarationStatus: 'تحديث حالة إقراراتي',
    viewOwnProfile: 'عرض ملفي الشخصي',
    
    // Status Labels
    draft: 'مسودة',
    pendingWarehouseSignature: 'بانتظار التوقيع',
    warehouseSigned: 'موقّع',
    sentToAdminOffice: 'مُرسل للإدارة',
    receivedByAdminOffice: 'مستلم',
    returnedToWarehouse: 'مُعاد',
    rejected: 'مرفوض',
    
    // Declaration Details
    declarationDetails: 'تفاصيل الإقرار',
    declarationInfo: 'معلومات الإقرار',
    declarationNumber: 'رقم الإقرار',
    updateStatus: 'تحديث الحالة',
    currentStatus: 'الحالة الحالية',
    timeline: 'المسار الزمني',
    viewTimeline: 'عرض المسار الزمني',
    backToManage: 'العودة للإدارة',
    createdBy: 'أنشئ بواسطة',
    lastUpdated: 'آخر تحديث',
    statusHistory: 'سجل الحالات',
    changedBy: 'تم التغيير بواسطة',
    changedAt: 'وقت التغيير',
    oldStatus: 'الحالة السابقة',
    newStatus: 'الحالة الجديدة',
    notes: 'ملاحظات',
    noNotes: 'لا توجد ملاحظات',
    statusUpdated: 'تم تحديث الحالة بنجاح',
    statusUpdateFailed: 'فشل تحديث الحالة. يرجى المحاولة مرة أخرى.',
    declarationNotFound: 'الإقرار غير موجود',
    
    // Create Declaration
    createDeclaration: 'إنشاء إقرار',
    createNewDeclaration: 'إنشاء إقرار جديد',
    enterDeclarationDetails: 'أدخل تفاصيل الإقرار أدناه',
    declarationNumberLabel: 'رقم الإقرار',
    declarationType: 'النوع',
    selectType: 'اختر النوع',
    entrance: 'دخول',
    exit: 'خروج',
    initialStatus: 'الحالة الأولية',
    selectStatus: 'اختر الحالة',
    declarationCreated: 'تم إنشاء الإقرار بنجاح',
    declarationCreationFailed: 'فشل إنشاء الإقرار. يرجى المحاولة مرة أخرى.',
    numberTooShort: 'رقم الإقرار يجب أن يكون 3 أرقام على الأقل',
    numberTooLong: 'رقم الإقرار طويل جداً',
    numbersOnly: 'يُسمح بالأرقام فقط',
    mustSelectType: 'يرجى اختيار نوع الإقرار',
    mustLogin: 'يتطلب تسجيل الدخول',
    numberExists: 'رقم الإقرار هذا موجود بالفعل',
    
    // Login/Signup
    signup: 'إنشاء حساب',
    createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    signupSuccess: 'تم إنشاء الحساب بنجاح',
    signupFailed: 'فشل إنشاء الحساب. يرجى المحاولة مرة أخرى.',
    enterUsername: 'يرجى إدخال اسم المستخدم',
    loggingIn: 'جاري تسجيل الدخول...',
    creatingAccount: 'جاري إنشاء الحساب...',
    
    // Messages
    success: 'نجح',
    error: 'خطأ',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    loadingData: 'جاري تحميل البيانات...',
    userRoleUpdated: 'تم تحديث صلاحية المستخدم بنجاح',
    userCreatedSuccess: 'تم إنشاء المستخدم بنجاح',
    fillAllFields: 'يرجى ملء جميع الحقول المطلوبة',
    userCreationFailed: 'فشل إنشاء المستخدم. يرجى المحاولة مرة أخرى.',
    permissionsDeleted: 'تم إزالة الصلاحيات بنجاح',
    
    // Dashboard Specific
    dashboardSubtitle: 'تتبع وإدارة جميع إقراراتك في مكان واحد',
    manageUsers: 'إدارة المستخدمين',
    viewAll: 'عرض الكل',
    noDeclarations: 'لا توجد إقرارات',
    
    // Manage Page
    manageDeclarations: 'إدارة الإقرارات',
    manageSubtitle: 'عرض وفلترة وإدارة جميع إقرارات النظام',
    searchPlaceholder: 'البحث برقم الإقرار أو المرسل...',
    filterBySender: 'تصفية حسب المرسل',
    allSenders: 'جميع المرسلين',
    filterByDate: 'تصفية حسب التاريخ',
    dateRange: 'نطاق التاريخ',
    from: 'من',
    to: 'إلى',
    clearFilters: 'مسح الفلاتر',
    selectAll: 'تحديد الكل',
    selected: 'محدد',
    exportSelected: 'تصدير المحدد',
    deleteSelected: 'حذف المحدد',
    noDeclarationsFound: 'لم يتم العثور على إقرارات',
    tryAdjustingFilters: 'جرب تعديل فلاتر البحث',
    bulkExport: 'التصدير الجماعي',
    
    // Keyboard navigation
    keyboardShortcuts: 'اختصارات لوحة المفاتيح',
    navigateRows: 'التنقل بين الصفوف',
    viewDetailsKey: 'عرض التفاصيل',
    selectRow: 'تحديد الصف',
    expandRow: 'توسيع الصف',
    deleteRow: 'حذف الصف',
    // Reports Page
    reportsTitle: 'التقارير والتحليلات',
    reportsSubtitle: 'تحليل شامل للإقرارات وأداء النظام',
    exportOptions: 'خيارات التصدير',
    statusBreakdown: 'تفصيل الحالات',
    declarationsOverTime: 'الإقرارات عبر الوقت',
    topUsers: 'أكثر المساهمين',
    by: 'بواسطة',
    
    // Profile Page
    myProfile: 'ملفي الشخصي',
    personalInformation: 'المعلومات الشخصية',
    accountSettings: 'إعدادات الحساب',
    securitySettings: 'إعدادات الأمان',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    updatePassword: 'تحديث كلمة المرور',
    passwordUpdated: 'تم تحديث كلمة المرور بنجاح',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    saveChanges: 'حفظ التغييرات',
    profileSubtitle: 'إدارة معلوماتك الشخصية وإعدادات الحساب',
    accountRole: 'صلاحية الحساب',
    passwordMinLength: '10 أحرف على الأقل',
    passwordUppercase: 'حرف كبير واحد على الأقل',
    passwordLowercase: 'حرف صغير واحد على الأقل',
    passwordNumber: 'رقم واحد على الأقل',
    passwordSpecialChar: 'رمز خاص واحد على الأقل (!@#$%^&*)',
    passwordStrength: 'قوة كلمة المرور',
    passwordRequirements: 'متطلبات كلمة المرور',
    requirements: 'متطلبات',
    weak: 'ضعيفة',
    medium: 'متوسطة',
    strong: 'قوية',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',
    usernameHint: '2-50 حرف، حروف وأرقام وشرطات سفلية',
    pleaseWait: 'الرجاء الانتظار...',
    skipToContent: 'تخطي إلى المحتوى الرئيسي',
    invalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    invalidData: 'البيانات المدخلة غير صحيحة',
    passwordChangeFailed: 'فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.',
    passwordChangeSuccess: 'تم تغيير كلمة المرور بنجاح',
    
    // Common Actions
    view: 'عرض',
    edit: 'تعديل',
    export: 'تصدير',
    import: 'استيراد',
    print: 'طباعة',
    close: 'إغلاق',
    save: 'حفظ',
    update: 'تحديث',
    confirm: 'تأكيد',
    
    // Manage
    declarations: 'الإقرارات',
    search: 'بحث',
    filter: 'فلتر',
    status: 'الحالة',
    allStatuses: 'جميع الحالات',
    declarationId: 'رقم الإقرار',
    type: 'النوع',
    sender: 'المرسل',
    createdDate: 'تاريخ الإنشاء',
    actions: 'الإجراءات',
    bulkActions: 'إجراءات جماعية',
    changeStatusTo: 'تغيير الحالة إلى...',
    bulkStatusChanged: 'تم تغيير الحالة',
    bulkDeleted: 'تم نقل العناصر إلى سلة المحذوفات',
    confirmBulkDelete: 'تأكيد الحذف الجماعي',
    bulkDeleteWarning: 'هل أنت متأكد من حذف {count} إقرار؟ سيتم نقلها إلى سلة المحذوفات.',
    sortAscending: 'ترتيب تصاعدي',
    sortDescending: 'ترتيب تنازلي',
    showing: 'عرض',
    of: 'من',
    
    // Reports
    reportsAnalytics: 'التقارير والتحليلات',
    overview: 'نظرة عامة',
    statusDistribution: 'توزيع الحالات',
    userActivity: 'نشاط المستخدمين',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportCSV: 'تصدير CSV',
    monthlyTrends: 'الاتجاهات الشهرية',
    completionRate: 'معدل الإنجاز',
    avgProcessingTime: 'متوسط المعالجة',
    days: 'أيام',
    savedFilters: 'الفلاتر المحفوظة',
    noSavedFilters: 'لا توجد فلاتر محفوظة',
    saveCurrentFilter: 'حفظ الفلتر الحالي',
    saveFilter: 'حفظ الفلتر',
    saveFilterDescription: 'احفظ إعدادات الفلتر للوصول السريع',
    filterNamePlaceholder: 'اسم الفلتر...',
    filterSaved: 'تم حفظ الفلتر بنجاح',
    filterDeleted: 'تم حذف الفلتر',
    filterApplied: 'تم تطبيق الفلتر',
    enterFilterName: 'يرجى إدخال اسم الفلتر',
    exportSuccess: 'تم تصدير التقرير بنجاح',
    changedDeclarationStatus: 'قام بتغيير حالة الإقرار',
    userLabel: 'مستخدم',
    switchLanguage: 'تبديل اللغة',
    
    // Navigation
    home: 'الرئيسية',
    maintenance: 'الصيانة',
    installApp: 'تثبيت التطبيق',
    auditLog: 'سجل التدقيق',
    checkingUpdates: 'جاري التحقق من التحديثات',
    noUpdates: 'لا توجد تحديثات',
    updateAvailable: 'تحديث متاح',
    pageWillReload: 'سيتم إعادة تحميل الصفحة لتطبيق التحديث...',
    youUsingLatest: 'أنت تستخدم أحدث إصدار',
    serviceWorkerNotRegistered: 'Service Worker غير مسجل',
    notSupported: 'غير مدعوم',
    browserNotSupport: 'متصفحك لا يدعم هذه الميزة',
    updateCheckFailed: 'فشل التحقق من التحديثات',
    forceUpdate: 'تحديث الآن',
    
    // Archive Files
    archiveFiles: 'ملفات الأرشيف',
    archiveFilesManagement: 'إدارة ملفات الأرشيف',
    addArchiveFile: 'إضافة ملف أرشيف',
    archiveNumber: 'رقم الأرشيف',
    archiveDescription: 'الوصف',
    declarationsCount: 'عدد الإقرارات',
    createdAt: 'تاريخ الإنشاء',
    noArchiveFiles: 'لا توجد ملفات أرشيف',
    addFirstArchiveFile: 'أنشئ أول ملف أرشيف',
    enterArchiveNumber: 'أدخل رقم الأرشيف',
    enterDescription: 'أدخل الوصف (اختياري)',
    add: 'إضافة',
    adding: 'جاري الإضافة...',
    archiveFileAdded: 'تم إنشاء ملف الأرشيف بنجاح',
    archiveFileDeleted: 'تم حذف ملف الأرشيف بنجاح',
    archiveFileExists: 'رقم الأرشيف هذا موجود بالفعل',
    cannotDeleteArchive: 'لا يمكن حذف أرشيف مرتبط بإقرارات',
    confirmDeleteArchive: 'هل أنت متأكد من حذف ملف الأرشيف هذا؟',
    unknown: 'غير معروف',
    noRecentDeclarations: 'لا توجد إقرارات حديثة',
    
    // Trash
    trashBin: 'سلة المحذوفات',
    deletedDate: 'تاريخ الحذف',
    daysRemaining: 'الأيام المتبقية',
    trashEmpty: 'سلة المحذوفات فارغة',
    noDeletedDeclarations: 'لا توجد إقرارات محذوفة حالياً',
    trashInfo: 'معلومات مهمة عن سلة المحذوفات:',
    trashRestore: 'يمكن استرجاع الإقرارات المحذوفة خلال 30 يوم من تاريخ الحذف',
    trashAutoDelete: 'بعد 30 يوم، سيتم حذف الإقرار نهائياً بشكل تلقائي',
    restore: 'استرجاع',
    permanentDelete: 'حذف نهائي',
    noActivitiesInPeriod: 'لا توجد نشاطات في الفترة المحددة',
    startCreating: 'لم يتم إنشاء أي إقرارات بعد. ابدأ بإنشاء إقرار جديد.',
    
    // Manage Page Extended
    allSendersFilter: 'جميع المرسلين',
    exportExcelBtn: 'تصدير إلى Excel',
    exportPDFBtn: 'تصدير إلى PDF',
    manageArchiveFiles: 'إدارة ملفات الأرشيف والإقرارات',
    movedToTrash: 'تم نقل الإقرار إلى سلة المحذوفات',
    alreadyDeleted: 'الإقرار محذوف بالفعل',
    
    // Maintenance
    maintenanceSystem: 'نظام الصيانة',
    itemName: 'اسم العنصر',
    frequency: 'التكرار',
    lastMaintenance: 'آخر صيانة',
    nextMaintenance: 'الصيانة القادمة',
    estimatedCost: 'التكلفة المقدرة',
    active: 'نشط',
    inactive: 'غير نشط',
    viewDetails: 'عرض التفاصيل',
    addMaintenanceItem: 'إضافة عنصر صيانة',
    addAsset: 'إضافة أصل',
    addVendor: 'إضافة مورد',
    assetName: 'اسم الأصل',
    vendorName: 'اسم المورد',
    contactPerson: 'جهة الاتصال',
    contactInfo: 'معلومات الاتصال',
    specialization: 'التخصص',
    location: 'الموقع',
    site: 'المنشأة',
    code: 'الرمز',
    phone: 'الهاتف',
    
    // Maintenance Status
    done: 'تم',
    notRequired: 'غير مطلوب',
    overdue: 'متأخر',
    
    // Frequency
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    semiannual: 'نصف سنوي',
    annual: 'سنوي',
    adHoc: 'عند الحاجة',
    
    // Asset Types
    electrical: 'كهربائي',
    plumbing: 'سباكة',
    hvac: 'تكييف',
    safety: 'أمان',
    equipment: 'معدات',
    building: 'مبنى',
    other: 'أخرى',
    
    // Maintenance Page
    maintenanceTitle: 'نظام الصيانة الدورية',
    maintenanceSubtitle: 'إدارة شاملة لعمليات الصيانة والأصول والموردين',
    maintenanceDashboard: 'لوحة التحكم',
    annualSchedule: 'الجدول السنوي',
    maintenanceItems: 'بنود الصيانة',
    assets: 'الأصول',
    vendors: 'الموردين',
    totalItems: 'إجمالي البنود',
    pendingTasks: 'المهام المعلقة',
    overdueTasks: 'المهام المتأخرة',
    completedThisMonth: 'المكتملة هذا الشهر',
    upcomingMaintenance: 'الصيانة القادمة',
    addItem: 'إضافة بند',
    editItem: 'تعديل البند',
    deleteItem: 'حذف البند',
    confirmDelete: 'تأكيد الحذف',
    deleteItemConfirm: 'هل أنت متأكد من حذف هذا البند؟',
    itemDeleted: 'تم حذف البند بنجاح',
    itemAdded: 'تم إضافة البند بنجاح',
    itemUpdated: 'تم تحديث البند بنجاح',
    description: 'الوصف',
    reminderDays: 'أيام التذكير',
    startDate: 'تاريخ البدء',
    selectAsset: 'اختر الأصل',
    selectVendor: 'اختر المورد',
    noAsset: 'بدون أصل',
    noVendor: 'بدون مورد',
    address: 'العنوان',
    purchaseDate: 'تاريخ الشراء',
    warrantyExpiry: 'انتهاء الضمان',
    
    // Offline Mode
    offline: 'غير متصل',
    syncing: 'جاري المزامنة...',
    pendingSync: 'عملية معلقة',
    offlineMessage: 'أنت غير متصل بالإنترنت. التغييرات ستُحفظ محلياً.',
    operationsPending: 'عملية في انتظار المزامنة',
    
    // Theme
    toggleTheme: 'تبديل السمة',
    lightMode: 'فاتح',
    darkMode: 'داكن',
    systemMode: 'النظام',
    
    // Analytics Page
    analyticsTitle: 'تحليلات متقدمة',
    analyticsSubtitle: 'رؤية شاملة لأداء نظام الإقرارات',
    declarationTrends: 'اتجاهات الإقرارات',
    statusAnalysis: 'تحليل الحالات',
    performanceMetrics: 'مقاييس الأداء',
    weeklyComparison: 'المقارنة الأسبوعية',
    monthlyOverview: 'النظرة الشهرية',
    yearlyStats: 'إحصائيات سنوية',
    averageTime: 'متوسط وقت المعالجة',
    peakHours: 'ساعات الذروة',
    efficiency: 'معدل الكفاءة',
    oneMonth: 'شهر واحد',
    threeMonths: '3 أشهر',
    sixMonths: '6 أشهر',
    oneYear: 'سنة',
    refreshData: 'تحديث',
    totalDeclarationsCard: 'إجمالي الإقرارات',
    completionRateCard: 'معدل الإنجاز',
    avgProcessingDaysCard: 'متوسط أيام المعالجة',
    inProcessingCard: 'قيد المعالجة',
    overviewTab: 'نظرة عامة',
    trendsTab: 'الاتجاهات',
    performanceTab: 'الأداء',
    statusDistributionChart: 'توزيع الحالات',
    statusDistributionDesc: 'نسبة كل حالة من إجمالي الإقرارات',
    typeDistributionChart: 'توزيع الأنواع',
    typeDistributionDesc: 'مقارنة بين إقرارات الدخول والخروج',
    weeklyActivityChart: 'النشاط الأسبوعي',
    weeklyActivityDesc: 'توزيع الإقرارات حسب أيام الأسبوع',
    monthlyTrendChart: 'الاتجاه الشهري',
    monthlyTrendDesc: 'تطور أعداد الإقرارات على مدار الأشهر',
    timeDistributionChart: 'التوزيع الزمني',
    timeDistributionDesc: 'أوقات الذروة لإنشاء الإقرارات خلال اليوم',
    performanceIndicatorsChart: 'مؤشرات الأداء',
    performanceIndicatorsDesc: 'نسبة تحقيق الأهداف المحددة',
    topSendersChart: 'أكثر المرسلين نشاطاً',
    topSendersDesc: 'ترتيب المستخدمين حسب عدد الإقرارات',
    totalLabel: 'الإجمالي',
    completedLabel: 'مكتملة',
    declarationCount: 'إقرار',
    inboundType: 'دخول',
    outboundType: 'خروج',
    completionRateMetric: 'معدل الإنجاز',
    processingSpeedMetric: 'سرعة المعالجة',
    efficiencyMetric: 'الكفاءة',
    delayed: 'متأخر',
    sunday: 'الأحد',
    monday: 'الإثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    
    // Additional Terms
    selectDate: 'اختر التاريخ',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    more: 'المزيد',
    less: 'أقل',
    details: 'التفاصيل',
    summary: 'ملخص',
    total: 'الإجمالي',
    average: 'المتوسط',
    minimum: 'الأدنى',
    maximum: 'الأقصى',
    count: 'العدد',
    percentage: 'النسبة',
    trend: 'الاتجاه',
    growth: 'نمو',
    decline: 'انخفاض',
    stable: 'مستقر',
    
    // Tooltips & Helpers
    clickToView: 'انقر لعرض التفاصيل',
    clickToEdit: 'انقر للتعديل',
    clickToDelete: 'انقر للحذف',
    dragToReorder: 'اسحب لإعادة الترتيب',
    requiredField: 'هذا الحقل مطلوب',
    optionalField: 'اختياري',
    
    // Notifications
    newNotification: 'إشعار جديد',
    markAsRead: 'تحديد كمقروء',
    markAllAsRead: 'تحديد الكل كمقروء',
    clearAll: 'مسح الكل',
    noNotifications: 'لا توجد إشعارات',
    
    // Time
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisYear: 'هذه السنة',
    lastWeek: 'الأسبوع الماضي',
    lastMonth: 'الشهر الماضي',
    lastYear: 'السنة الماضية',
    custom: 'نطاق مخصص',
    
    // Onboarding
    onboardingDashboardTitle: 'نظرة عامة على لوحة التحكم',
    onboardingDashboardDesc: 'احصل على نظرة شاملة لجميع إقراراتك وإحصائيات النظام في لمحة واحدة.',
    onboardingDeclarationsTitle: 'إدارة الإقرارات',
    onboardingDeclarationsDesc: 'أنشئ وتتبع وأدر جميع إقراراتك بسير عمل سلس.',
    onboardingReportsTitle: 'التقارير والتحليلات',
    onboardingReportsDesc: 'أنشئ تقارير مفصلة واحصل على رؤى من بيانات إقراراتك.',
    onboardingMaintenanceTitle: 'نظام الصيانة',
    onboardingMaintenanceDesc: 'جدول وتتبع مهام الصيانة للحفاظ على سير العمل بسلاسة.',
    onboardingNotificationsTitle: 'البقاء على اطلاع',
    onboardingNotificationsDesc: 'استلم إشعارات فورية حول التحديثات والتغييرات المهمة.',
    onboardingSkip: 'تخطي',
    onboardingNext: 'التالي',
    onboardingPrevious: 'السابق',
    onboardingComplete: 'ابدأ الآن',
    
    // 404 Page
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundDesc: 'عذراً! الصفحة التي تبحث عنها غير موجودة.',
    returnToHome: 'العودة للرئيسية',
    
    // Change Status
    changeStatus: 'تغيير الحالة',
    
    // Reports & Analytics Tabs (new keys only)
    exportTab: 'تصدير',
    adminStatsTab: 'إحصائيات المدير',
    
    // Pagination
    rowsPerPage: 'عدد الصفوف',
    firstPage: 'الصفحة الأولى',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    lastPage: 'الصفحة الأخيرة',
    page: 'صفحة',
    
    // Dashboard Charts
    quickStatsOverview: 'نظرة سريعة على الإحصائيات',
    declarationBreakdown: 'توزيع الإقرارات حسب الحالة',
    
    // Date range presets
    last7Days: 'آخر 7 أيام',
    last30Days: 'آخر 30 يوم',
    last90Days: 'آخر 90 يوم',
    
    // Dashboard Actions
    declarationRestored: 'تم استرجاع الإقرار بنجاح',
    declarationPermanentlyDeleted: 'تم حذف الإقرار نهائياً',
    permanentDeleteWarning: '⚠️ تحذير: سيتم حذف الإقرار نهائياً ولا يمكن استرجاعه. هل أنت متأكد؟',
    
    // Profile Page Extended
    personalData: 'البيانات الشخصية',
    usernameLabel: 'اسم المستخدم',
    emailLabel: 'البريد الإلكتروني',
    functionalRole: 'الدور الوظيفي',
    resetChanges: 'إعادة تعيين',
    saving: 'جاري الحفظ...',
    saveEdits: 'حفظ التعديلات',
    changePasswordTitle: 'تغيير كلمة المرور',
    newPasswordLabel: 'كلمة المرور الجديدة',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    updatingPassword: 'جاري التحديث...',
    updatePasswordBtn: 'تحديث كلمة المرور',
    dataUpdated: 'تم تحديث بياناتك الشخصية بنجاح',
    usernameTaken: 'اسم المستخدم مستخدم بالفعل',
    emailTaken: 'البريد الإلكتروني مستخدم بالفعل',
    dataUpdateFailed: 'فشل تحديث البيانات',
    profileDataError: 'خطأ في البيانات',
    passwordsNotMatch: 'كلمتا المرور غير متطابقتين',
    
    // Maintenance Extended
    maintenanceItemsTitle: 'إدارة بنود الصيانة',
    maintenanceItemsDesc: 'تحديد المهام الدورية والمتطلبات',
    addNewItem: 'إضافة بند جديد',
    editMaintenanceItem: 'تعديل بند الصيانة',
    addMaintenanceItemTitle: 'إضافة بند صيانة جديد',
    itemNameLabel: 'اسم البند',
    itemNamePlaceholder: 'مثال: صيانة مكيف الهواء - الطابق الأول',
    linkedAsset: 'الأصل المرتبط',
    selectAssetPlaceholder: 'اختر الأصل',
    noAssetOption: 'بدون أصل',
    executingParty: 'الجهة المنفذة',
    selectVendorPlaceholder: 'اختر المورد',
    noVendorOption: 'بدون مورد',
    repetition: 'التكرار',
    startDateLabel: 'تاريخ البداية',
    estimatedCostLabel: 'التكلفة المقدرة',
    reminderBeforeDays: 'التذكير قبل (أيام)',
    descriptionLabel: 'الوصف',
    notesLabel: 'ملاحظات',
    activeItem: 'بند نشط',
    itemUpdatedSuccess: 'تم تحديث البند بنجاح',
    itemAddedSuccess: 'تم إضافة البند بنجاح',
    scheduleGeneratedSuccess: 'تم إضافة البند وتوليد الجدول السنوي بنجاح',
    confirmDeleteItem: 'هل أنت متأكد من حذف هذا البند؟ سيتم حذف جميع الجداول المرتبطة به.',
    itemDeletedSuccess: 'تم حذف البند بنجاح',
    
    // Assets Extended
    assetsTitle: 'إدارة الأصول والمعدات',
    assetsDesc: 'تسجيل ومتابعة الأصول والمعدات',
    addNewAsset: 'إضافة أصل جديد',
    editAssetTitle: 'تعديل الأصل',
    addAssetTitle: 'إضافة أصل جديد',
    assetNameLabel: 'اسم الأصل',
    codeLabel: 'الرمز/الكود',
    typeLabel: 'النوع',
    locationLabel: 'الموقع',
    siteLabel: 'المنشأة',
    purchaseDateLabel: 'تاريخ الشراء',
    warrantyExpiryLabel: 'تاريخ انتهاء الضمان',
    activeAsset: 'أصل نشط',
    assetUpdatedSuccess: 'تم تحديث الأصل بنجاح',
    assetAddedSuccess: 'تم إضافة الأصل بنجاح',
    confirmDeleteAsset: 'هل أنت متأكد من حذف هذا الأصل؟',
    assetDeletedSuccess: 'تم حذف الأصل بنجاح',
    
    // Vendors Extended
    vendorsTitle: 'إدارة الموردين وشركات الصيانة',
    vendorsDesc: 'إضافة وتعديل معلومات الموردين',
    addNewVendor: 'إضافة مورد جديد',
    editVendorTitle: 'تعديل المورد',
    addVendorTitle: 'إضافة مورد جديد',
    vendorNameLabel: 'اسم المورد',
    responsiblePerson: 'الشخص المسؤول',
    phoneLabel: 'رقم الهاتف',
    emailFieldLabel: 'البريد الإلكتروني',
    addressLabel: 'العنوان',
    specializationLabel: 'التخصص',
    specializationPlaceholder: 'مثال: كهرباء، سباكة، تكييف',
    activeVendor: 'مورد نشط',
    vendorUpdatedSuccess: 'تم تحديث المورد بنجاح',
    vendorAddedSuccess: 'تم إضافة المورد بنجاح',
    confirmDeleteVendor: 'هل أنت متأكد من حذف هذا المورد؟',
    vendorDeletedSuccess: 'تم حذف المورد بنجاح',
    
    // Audit Logs
    auditLogsTitle: 'سجل التدقيق (Audit Logs)',
    auditLogsDesc: 'سجل شامل لجميع العمليات المهمة في النظام',
    totalLogs: 'إجمالي السجلات',
    createOperations: 'عمليات إنشاء',
    updateOperations: 'عمليات تحديث',
    deleteOperations: 'عمليات حذف',
    searchByIdOrUser: 'بحث بالمعرف أو المستخدم...',
    operationType: 'نوع العملية',
    allOperations: 'جميع العمليات',
    createAction: 'إنشاء',
    updateAction: 'تحديث',
    deleteAction: 'حذف',
    assignRole: 'تعيين دور',
    updateRole: 'تحديث دور',
    removeRole: 'إزالة دور',
    tableFilter: 'الجدول',
    allTables: 'جميع الجداول',
    declarationsTable: 'الإقرارات',
    userRolesTable: 'أدوار المستخدمين',
    maintenanceItemsTable: 'بنود الصيانة',
    maintenanceScheduleTable: 'جدول الصيانة',
    logsTableTitle: 'السجلات',
    dateTimeColumn: 'التاريخ والوقت',
    userColumn: 'المستخدم',
    operationColumn: 'العملية',
    tableColumn: 'الجدول',
    idColumn: 'المعرف',
    unauthorized: 'غير مصرح',
    adminOnlyPage: 'هذه الصفحة متاحة للمسؤولين فقط',
    unknownUser: 'غير معروف',
    failedLoginAttempt: 'محاولة دخول فاشلة',
    
    // Declaration Details Page
    backToDashboard: 'العودة للوحة التحكم',
    declarationDetailsTitle: 'تفاصيل الإقرار',
    detailsTab: 'التفاصيل',
    timelineTab: 'المسار',
    coreInfo: 'المعلومات الأساسية',
    declarationTypeLabel: 'نوع الإقرار',
    statusLabel: 'الحالة',
    createdDateLabel: 'تاريخ الإنشاء',
    lastUpdateLabel: 'آخر تحديث',
    archiveFileLabel: 'ملف الأرشفة',
    selectArchiveFile: 'اختر ملف الأرشفة',
    noArchiveFile: 'بدون ملف أرشفة',
    editBtn: 'تعديل',
    saveBtn: 'حفظ',
    cancelBtn: 'إلغاء',
    senderInfo: 'معلومات المرسل',
    usernameColumn: 'اسم المستخدم',
    emailColumn: 'البريد الإلكتروني',
    declarationTimeline: 'الخط الزمني للإقرار',
    noHistoryRecords: 'لا يوجد سجل تغييرات لهذا الإقرار',
    declarationNotExist: 'الإقرار غير موجود',
    archiveFileUpdated: 'تم تحديث ملف الأرشفة',
    archiveFileUpdateFailed: 'فشل تحديث ملف الأرشفة',
    statusUpdateSuccess: 'تم تحديث حالة الإقرار',
    statusUpdateError: 'فشل تحديث الحالة',
    
    // Status Labels Full
    statusDraft: 'مسودة',
    statusPendingWarehouseSignature: 'بانتظار توقيع المخزن',
    statusWarehouseSigned: 'موقّع من المخزن',
    statusSentToAdminOffice: 'مُرسل إلى المكتب الإداري',
    statusReceivedByAdminOffice: 'مستلم من المكتب الإداري',
    statusReturnedToWarehouse: 'مُعاد إلى المخزن للأرشفة',
    statusArchived: 'مؤرشف',
    statusRejected: 'مرفوض / يحتاج إلى تصحيح',
    
    // Forgot Password Page
    forgotPasswordTitle: 'نسيت كلمة المرور؟',
    forgotPasswordDesc: 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور',
    emailAddress: 'البريد الإلكتروني',
    sendResetLink: 'إرسال رابط إعادة التعيين',
    sendingResetLink: 'جاري الإرسال...',
    resetLinkSent: 'تم الإرسال بنجاح',
    resetLinkSentDesc: 'تحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور',
    resetLinkFailed: 'فشل إرسال رسالة إعادة التعيين',
    backToLogin: 'العودة لتسجيل الدخول',
    
    // Reset Password Page
    invalidResetLink: 'رابط غير صالح أو منتهي الصلاحية',
    
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'ar';
  });

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'en' ? 'ar' : 'en';
      localStorage.setItem('app-language', newLang);
      
      // Update HTML attributes immediately without reload
      document.documentElement.lang = newLang;
      document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
      
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  // Set initial HTML attributes
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
