import { useEffect, useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { useLanguage } from '@/contexts/LanguageContext';

export interface BoxDispatch {
  id: string;
  serial_no: number;
  dispatch_no: string;
  dispatch_date: string;
  department_id: string | null;
  department_name: string;
  signer_name: string;
  signer_title: string | null;
  shipping_company: string | null;
  destination: 'morocco' | 'uzbekistan' | 'unspecified';
  notes: string | null;
  status: 'draft' | 'approved' | 'cancelled';
  created_by: string | null;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface BoxDispatchItem {
  id: string;
  dispatch_id: string;
  receipt_id: string;
  qty_dispatched: number;
  notes: string | null;
}

export interface DispatchInput {
  dispatch_date: string;
  department_id: string | null;
  department_name: string;
  signer_name: string;
  signer_title: string | null;
  shipping_company: string | null;
  destination: 'morocco' | 'uzbekistan' | 'unspecified';
  notes: string | null;
  items: Array<{ receipt_id: string; qty_dispatched: number; notes?: string | null }>;
}

export function useBoxDispatches() {
  const { user } = useAuth();
  const { toast } = useToast();
  const { t } = useLanguage();
  const [dispatches, setDispatches] = useState<BoxDispatch[]>([]);
  const [items, setItems] = useState<BoxDispatchItem[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchAll = useCallback(async () => {
    setLoading(true);
    const [dRes, iRes] = await Promise.all([
      supabase
        .from('box_dispatches')
        .select('*')
        .is('deleted_at', null)
        .order('dispatch_date', { ascending: false })
        .order('serial_no', { ascending: false }),
      supabase.from('box_dispatch_items').select('*'),
    ]);
    if (dRes.error) {
      console.error('[useBoxDispatches]', dRes.error);
      toast({ title: t('error'), description: dRes.error.message, variant: 'destructive' });
    } else {
      setDispatches((dRes.data ?? []) as BoxDispatch[]);
    }
    if (iRes.error) {
      console.error('[useBoxDispatches:items]', iRes.error);
    } else {
      setItems((iRes.data ?? []) as BoxDispatchItem[]);
    }
    setLoading(false);
  }, [toast, t]);

  useEffect(() => {
    fetchAll();
    const ch = supabase
      .channel('box_dispatches_changes')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'box_dispatches' }, () => fetchAll())
      .on('postgres_changes', { event: '*', schema: 'public', table: 'box_dispatch_items' }, () => fetchAll())
      .subscribe();
    return () => {
      supabase.removeChannel(ch);
    };
  }, [fetchAll]);

  /**
   * Create a draft dispatch with its line items.
   */
  const createDispatch = useCallback(
    async (input: DispatchInput): Promise<BoxDispatch | null> => {
      if (!user?.id) {
        toast({ title: t('error'), description: t('mustBeLoggedIn'), variant: 'destructive' });
        return null;
      }
      if (input.items.length === 0) {
        toast({ title: t('error'), description: t('noItemsSelected'), variant: 'destructive' });
        return null;
      }
      const { data: hdr, error: hErr } = await supabase
        .from('box_dispatches')
        .insert([
          {
            // dispatch_no is auto-generated by DB trigger; placeholder satisfies TS types.
            dispatch_no: '',
            dispatch_date: input.dispatch_date,
            department_id: input.department_id,
            department_name: input.department_name,
            signer_name: input.signer_name,
            signer_title: input.signer_title,
            shipping_company: input.shipping_company,
            destination: input.destination,
            notes: input.notes,
            status: 'draft',
            created_by: user.id,
          },
        ])
        .select()
        .single();
      if (hErr || !hdr) {
        toast({ title: t('error'), description: hErr?.message ?? 'error', variant: 'destructive' });
        return null;
      }
      const lines = input.items.map((it) => ({
        dispatch_id: hdr.id,
        receipt_id: it.receipt_id,
        qty_dispatched: it.qty_dispatched,
        notes: it.notes ?? null,
      }));
      const { error: lErr } = await supabase.from('box_dispatch_items').insert(lines);
      if (lErr) {
        // Rollback header
        await supabase.from('box_dispatches').delete().eq('id', hdr.id);
        toast({ title: t('error'), description: lErr.message, variant: 'destructive' });
        return null;
      }
      toast({ title: t('success'), description: t('dispatchCreated') });
      return hdr as BoxDispatch;
    },
    [user?.id, toast, t]
  );

  /**
   * Approve a dispatch — calls the SECURITY DEFINER function which atomically
   * subtracts qty from receipts (status='dispatched' when fully consumed).
   */
  const approveDispatch = useCallback(
    async (dispatchId: string) => {
      if (!user?.id) return false;
      const { error: rpcErr } = await supabase.rpc('apply_dispatch_quantities', {
        p_dispatch_id: dispatchId,
      });
      if (rpcErr) {
        toast({ title: t('error'), description: rpcErr.message, variant: 'destructive' });
        return false;
      }
      const { error: uErr } = await supabase
        .from('box_dispatches')
        .update({
          status: 'approved',
          approved_by: user.id,
          approved_at: new Date().toISOString(),
        })
        .eq('id', dispatchId);
      if (uErr) {
        toast({ title: t('error'), description: uErr.message, variant: 'destructive' });
        return false;
      }
      toast({ title: t('success'), description: t('dispatchApproved') });
      return true;
    },
    [user?.id, toast, t]
  );

  const cancelDispatch = useCallback(
    async (dispatchId: string) => {
      const { error } = await supabase
        .from('box_dispatches')
        .update({ status: 'cancelled' })
        .eq('id', dispatchId);
      if (error) {
        toast({ title: t('error'), description: error.message, variant: 'destructive' });
        return false;
      }
      toast({ title: t('success'), description: t('dispatchCancelled') });
      return true;
    },
    [toast, t]
  );

  const deleteDispatch = useCallback(
    async (dispatchId: string) => {
      if (!user?.id) return false;
      const { error } = await supabase
        .from('box_dispatches')
        .update({ deleted_at: new Date().toISOString(), deleted_by: user.id })
        .eq('id', dispatchId);
      if (error) {
        toast({ title: t('error'), description: error.message, variant: 'destructive' });
        return false;
      }
      toast({ title: t('success'), description: t('deleted') });
      return true;
    },
    [user?.id, toast, t]
  );

  return {
    dispatches,
    items,
    loading,
    refetch: fetchAll,
    createDispatch,
    approveDispatch,
    cancelDispatch,
    deleteDispatch,
  };
}